// Code generated by ent, DO NOT EDIT.

package internal

import "context"

// SchemaConfig represents alternative schema names for all tables
// that can be passed at runtime.
type SchemaConfig struct {
	API                   string // API table.
	Area                  string // Area table.
	Dictionary            string // Dictionary table.
	DictionaryDetail      string // DictionaryDetail table.
	Logs                  string // Logs table.
	Menu                  string // Menu table.
	MenuParam             string // MenuParam table.
	Role                  string // Role table.
	RoleMenus             string // Role-menus->Menu table.
	Sms                   string // Sms table.
	SmsLog                string // SmsLog table.
	Survey                string // Survey table.
	SurveyQuestion        string // SurveyQuestion table.
	SurveyResponse        string // SurveyResponse table.
	SurveyResponseAnswers string // SurveyResponseAnswers table.
	Token                 string // Token table.
	User                  string // User table.
	UserRoles             string // User-roles->Role table.
}

type schemaCtxKey struct{}

// SchemaConfigFromContext returns a SchemaConfig stored inside a context, or empty if there isn't one.
func SchemaConfigFromContext(ctx context.Context) SchemaConfig {
	config, _ := ctx.Value(schemaCtxKey{}).(SchemaConfig)
	return config
}

// NewSchemaConfigContext returns a new context with the given SchemaConfig attached.
func NewSchemaConfigContext(parent context.Context, config SchemaConfig) context.Context {
	return context.WithValue(parent, schemaCtxKey{}, config)
}
