// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"kcers-survey/biz/dal/casbin"
	"kcers-survey/biz/mw"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {

	// your code ...

	// Login .
	//	@Summary		登录 Summary
	//	@Description	登录 Description
	//	@Param			request	body		user.LoginReq	true	"query params"
	//	@Success		200		{object}	utils.Response
	//	@router			/service/login [POST]
	r.POST("/service/login", mw.GetJWTMw(casbin.CasbinEnforcer()).LoginHandler)
	r.POST("/service/logout", mw.GetJWTMw(casbin.CasbinEnforcer()).LogoutHandler)
	r.POST("/service/refresh_token", mw.GetJWTMw(casbin.CasbinEnforcer()).RefreshHandler)

}
