// Code generated by ent, DO NOT EDIT.

package area

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the area type in the database.
	Label = "area"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDelete holds the string denoting the delete field in the database.
	FieldDelete = "delete"
	// FieldCreatedID holds the string denoting the created_id field in the database.
	FieldCreatedID = "created_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldWholeName holds the string denoting the whole_name field in the database.
	FieldWholeName = "whole_name"
	// FieldLon holds the string denoting the lon field in the database.
	FieldLon = "lon"
	// FieldLat holds the string denoting the lat field in the database.
	FieldLat = "lat"
	// FieldCityCode holds the string denoting the city_code field in the database.
	FieldCityCode = "city_code"
	// FieldZipCode holds the string denoting the zip_code field in the database.
	FieldZipCode = "zip_code"
	// FieldAreaCode holds the string denoting the area_code field in the database.
	FieldAreaCode = "area_code"
	// FieldPinYin holds the string denoting the pin_yin field in the database.
	FieldPinYin = "pin_yin"
	// FieldSimplePy holds the string denoting the simple_py field in the database.
	FieldSimplePy = "simple_py"
	// FieldPerPinYin holds the string denoting the per_pin_yin field in the database.
	FieldPerPinYin = "per_pin_yin"
	// Table holds the table name of the area in the database.
	Table = "sys_area"
)

// Columns holds all SQL columns for area fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDelete,
	FieldCreatedID,
	FieldStatus,
	FieldParentID,
	FieldLevel,
	FieldName,
	FieldWholeName,
	FieldLon,
	FieldLat,
	FieldCityCode,
	FieldZipCode,
	FieldAreaCode,
	FieldPinYin,
	FieldSimplePy,
	FieldPerPinYin,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDelete holds the default value on creation for the "delete" field.
	DefaultDelete int64
	// DefaultCreatedID holds the default value on creation for the "created_id" field.
	DefaultCreatedID int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int64
)

// OrderOption defines the ordering options for the Area queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDelete orders the results by the delete field.
func ByDelete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelete, opts...).ToFunc()
}

// ByCreatedID orders the results by the created_id field.
func ByCreatedID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByWholeName orders the results by the whole_name field.
func ByWholeName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWholeName, opts...).ToFunc()
}

// ByLon orders the results by the lon field.
func ByLon(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLon, opts...).ToFunc()
}

// ByLat orders the results by the lat field.
func ByLat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLat, opts...).ToFunc()
}

// ByCityCode orders the results by the city_code field.
func ByCityCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCityCode, opts...).ToFunc()
}

// ByZipCode orders the results by the zip_code field.
func ByZipCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldZipCode, opts...).ToFunc()
}

// ByAreaCode orders the results by the area_code field.
func ByAreaCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAreaCode, opts...).ToFunc()
}

// ByPinYin orders the results by the pin_yin field.
func ByPinYin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPinYin, opts...).ToFunc()
}

// BySimplePy orders the results by the simple_py field.
func BySimplePy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSimplePy, opts...).ToFunc()
}

// ByPerPinYin orders the results by the per_pin_yin field.
func ByPerPinYin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerPinYin, opts...).ToFunc()
}
