// Code generated by hertz generator.

package pub

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	base "kcers-survey/idl_gen/model/base"
	pub "kcers-survey/idl_gen/model/pub"
)

// Upload .
// @router /service/pub/upload/ [POST]
func Upload(ctx context.Context, c *app.RequestContext) {
	var err error
	var req pub.UploadReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, resp)
}
