// Code generated by ent, DO NOT EDIT.

package surveyquestionoptions

import (
	"kcers-survey/biz/dal/db/mysql/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldUpdatedAt, v))
}

// Delete applies equality check predicate on the "delete" field. It's identical to DeleteEQ.
func Delete(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldDelete, v))
}

// CreatedID applies equality check predicate on the "created_id" field. It's identical to CreatedIDEQ.
func CreatedID(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldCreatedID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldStatus, v))
}

// SurveyQuestionID applies equality check predicate on the "survey_question_id" field. It's identical to SurveyQuestionIDEQ.
func SurveyQuestionID(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldSurveyQuestionID, v))
}

// Serial applies equality check predicate on the "serial" field. It's identical to SerialEQ.
func Serial(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldSerial, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldContent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotNull(FieldUpdatedAt))
}

// DeleteEQ applies the EQ predicate on the "delete" field.
func DeleteEQ(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldDelete, v))
}

// DeleteNEQ applies the NEQ predicate on the "delete" field.
func DeleteNEQ(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNEQ(FieldDelete, v))
}

// DeleteIn applies the In predicate on the "delete" field.
func DeleteIn(vs ...int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIn(FieldDelete, vs...))
}

// DeleteNotIn applies the NotIn predicate on the "delete" field.
func DeleteNotIn(vs ...int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotIn(FieldDelete, vs...))
}

// DeleteGT applies the GT predicate on the "delete" field.
func DeleteGT(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGT(FieldDelete, v))
}

// DeleteGTE applies the GTE predicate on the "delete" field.
func DeleteGTE(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGTE(FieldDelete, v))
}

// DeleteLT applies the LT predicate on the "delete" field.
func DeleteLT(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLT(FieldDelete, v))
}

// DeleteLTE applies the LTE predicate on the "delete" field.
func DeleteLTE(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLTE(FieldDelete, v))
}

// DeleteIsNil applies the IsNil predicate on the "delete" field.
func DeleteIsNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIsNull(FieldDelete))
}

// DeleteNotNil applies the NotNil predicate on the "delete" field.
func DeleteNotNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotNull(FieldDelete))
}

// CreatedIDEQ applies the EQ predicate on the "created_id" field.
func CreatedIDEQ(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldCreatedID, v))
}

// CreatedIDNEQ applies the NEQ predicate on the "created_id" field.
func CreatedIDNEQ(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNEQ(FieldCreatedID, v))
}

// CreatedIDIn applies the In predicate on the "created_id" field.
func CreatedIDIn(vs ...int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIn(FieldCreatedID, vs...))
}

// CreatedIDNotIn applies the NotIn predicate on the "created_id" field.
func CreatedIDNotIn(vs ...int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotIn(FieldCreatedID, vs...))
}

// CreatedIDGT applies the GT predicate on the "created_id" field.
func CreatedIDGT(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGT(FieldCreatedID, v))
}

// CreatedIDGTE applies the GTE predicate on the "created_id" field.
func CreatedIDGTE(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGTE(FieldCreatedID, v))
}

// CreatedIDLT applies the LT predicate on the "created_id" field.
func CreatedIDLT(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLT(FieldCreatedID, v))
}

// CreatedIDLTE applies the LTE predicate on the "created_id" field.
func CreatedIDLTE(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLTE(FieldCreatedID, v))
}

// CreatedIDIsNil applies the IsNil predicate on the "created_id" field.
func CreatedIDIsNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIsNull(FieldCreatedID))
}

// CreatedIDNotNil applies the NotNil predicate on the "created_id" field.
func CreatedIDNotNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotNull(FieldCreatedID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotNull(FieldStatus))
}

// SurveyQuestionIDEQ applies the EQ predicate on the "survey_question_id" field.
func SurveyQuestionIDEQ(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldSurveyQuestionID, v))
}

// SurveyQuestionIDNEQ applies the NEQ predicate on the "survey_question_id" field.
func SurveyQuestionIDNEQ(v int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNEQ(FieldSurveyQuestionID, v))
}

// SurveyQuestionIDIn applies the In predicate on the "survey_question_id" field.
func SurveyQuestionIDIn(vs ...int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIn(FieldSurveyQuestionID, vs...))
}

// SurveyQuestionIDNotIn applies the NotIn predicate on the "survey_question_id" field.
func SurveyQuestionIDNotIn(vs ...int64) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotIn(FieldSurveyQuestionID, vs...))
}

// SurveyQuestionIDIsNil applies the IsNil predicate on the "survey_question_id" field.
func SurveyQuestionIDIsNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIsNull(FieldSurveyQuestionID))
}

// SurveyQuestionIDNotNil applies the NotNil predicate on the "survey_question_id" field.
func SurveyQuestionIDNotNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotNull(FieldSurveyQuestionID))
}

// SerialEQ applies the EQ predicate on the "serial" field.
func SerialEQ(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldSerial, v))
}

// SerialNEQ applies the NEQ predicate on the "serial" field.
func SerialNEQ(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNEQ(FieldSerial, v))
}

// SerialIn applies the In predicate on the "serial" field.
func SerialIn(vs ...string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIn(FieldSerial, vs...))
}

// SerialNotIn applies the NotIn predicate on the "serial" field.
func SerialNotIn(vs ...string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotIn(FieldSerial, vs...))
}

// SerialGT applies the GT predicate on the "serial" field.
func SerialGT(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGT(FieldSerial, v))
}

// SerialGTE applies the GTE predicate on the "serial" field.
func SerialGTE(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGTE(FieldSerial, v))
}

// SerialLT applies the LT predicate on the "serial" field.
func SerialLT(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLT(FieldSerial, v))
}

// SerialLTE applies the LTE predicate on the "serial" field.
func SerialLTE(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLTE(FieldSerial, v))
}

// SerialContains applies the Contains predicate on the "serial" field.
func SerialContains(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldContains(FieldSerial, v))
}

// SerialHasPrefix applies the HasPrefix predicate on the "serial" field.
func SerialHasPrefix(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldHasPrefix(FieldSerial, v))
}

// SerialHasSuffix applies the HasSuffix predicate on the "serial" field.
func SerialHasSuffix(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldHasSuffix(FieldSerial, v))
}

// SerialIsNil applies the IsNil predicate on the "serial" field.
func SerialIsNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIsNull(FieldSerial))
}

// SerialNotNil applies the NotNil predicate on the "serial" field.
func SerialNotNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotNull(FieldSerial))
}

// SerialEqualFold applies the EqualFold predicate on the "serial" field.
func SerialEqualFold(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEqualFold(FieldSerial, v))
}

// SerialContainsFold applies the ContainsFold predicate on the "serial" field.
func SerialContainsFold(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldContainsFold(FieldSerial, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.FieldContainsFold(FieldContent, v))
}

// HasQuestion applies the HasEdge predicate on the "question" edge.
func HasQuestion() predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, QuestionTable, QuestionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuestionWith applies the HasEdge predicate on the "question" edge with a given conditions (other predicates).
func HasQuestionWith(preds ...predicate.SurveyQuestion) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(func(s *sql.Selector) {
		step := newQuestionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SurveyQuestionOptions) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SurveyQuestionOptions) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SurveyQuestionOptions) predicate.SurveyQuestionOptions {
	return predicate.SurveyQuestionOptions(sql.NotPredicates(p))
}
