Name: Admin
IsProd: true
Host: 0.0.0.0
Port: 9039
Timeout: 30000
Domain: http://127.0.0.1/
PicHost: http://127.0.0.1

Captcha:
  KeyLong: 5
  ImgWidth: 240
  ImgHeight: 80

Auth:
  OAuthKey: OauthJf3z1n2xxx2cr1
  AccessSecret: D86VKDtsJf3z1nxxxxtsJf3z1n5
  AccessExpire: 259200 # seconds, 3 days

Redis:
  Host: 127.0.0.1:6379
  Password:

MySQL:
  Host: root:root@tcp(127.0.0.1:3306)/saas?parseTime=True
  Salt: root

PostgreSQL:
  Host: postgresql://postgres:root@127.0.0.1/postgres
  Salt: YOUR_SALT

Casbin:
  ModelText: |
    [request_definition]
    r = sub, obj, act
    [policy_definition]
    p = sub, obj, act
    [role_definition]
    g = _, _
    [policy_effect]
    e = some(where (p.eft == allow))
    [matchers]
    m = r.sub == p.sub && keyMatch2(r.obj,p.obj) && r.act == p.act

Wechat:
  appid:
  app_secret:
  mch_id:
  api_key:
  api_v3_key:
  cert_file_content: ./config/cert/wechat/apiclient_cert.pem
  key_file_content: ./config/cert/wechat/apiclient_key.pem
  pkcs12_file_content: ./config/cert/wechat/apiclient_cert.p12
  serial_no:
  notify_url: https://127.0.0.1/service/payment/WXNotify
  wechat_pay_serial_no:
  rsa_public_key_path:
  certificate_key_path: ./config/cert/wechat/wechatpay_platform.pem

Minio:
  EndPoint : 127.0.0.1:9000
  AccessKeyID : 123987
  SecretAccessKey : 987123
  UseSSL : false
  VideoBucketName : files
  ImgBucketName : imagebucket
  Url : http://127.0.0.1:9000

Alipay: # 以下配置文件为新沙箱环境配置
  appid:
  private_key:
  app_public_cert_content:
  alipay_root_cert_content:
  alipay_public_cert_content:
  notify_url:

Aliyun:
  Access:
    AccessKeyId:
    AccessKeySecret:
  Sms:
    Captcha:
      SignName:
      TemplateCode :

Swagger:
  url : http://182.92.143.234:9039/swagger/doc.json