// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kcers-survey/biz/dal/db/mysql/ent/survey"
	"kcers-survey/biz/dal/db/mysql/ent/surveyresponse"
	"kcers-survey/biz/dal/db/mysql/ent/surveyresponseanswers"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SurveyResponseCreate is the builder for creating a SurveyResponse entity.
type SurveyResponseCreate struct {
	config
	mutation *SurveyResponseMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SurveyResponseCreate) SetCreatedAt(v time.Time) *SurveyResponseCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableCreatedAt(v *time.Time) *SurveyResponseCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SurveyResponseCreate) SetUpdatedAt(v time.Time) *SurveyResponseCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableUpdatedAt(v *time.Time) *SurveyResponseCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDelete sets the "delete" field.
func (_c *SurveyResponseCreate) SetDelete(v int64) *SurveyResponseCreate {
	_c.mutation.SetDelete(v)
	return _c
}

// SetNillableDelete sets the "delete" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableDelete(v *int64) *SurveyResponseCreate {
	if v != nil {
		_c.SetDelete(*v)
	}
	return _c
}

// SetCreatedID sets the "created_id" field.
func (_c *SurveyResponseCreate) SetCreatedID(v int64) *SurveyResponseCreate {
	_c.mutation.SetCreatedID(v)
	return _c
}

// SetNillableCreatedID sets the "created_id" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableCreatedID(v *int64) *SurveyResponseCreate {
	if v != nil {
		_c.SetCreatedID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SurveyResponseCreate) SetStatus(v int64) *SurveyResponseCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableStatus(v *int64) *SurveyResponseCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSurveyID sets the "survey_id" field.
func (_c *SurveyResponseCreate) SetSurveyID(v int64) *SurveyResponseCreate {
	_c.mutation.SetSurveyID(v)
	return _c
}

// SetNillableSurveyID sets the "survey_id" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableSurveyID(v *int64) *SurveyResponseCreate {
	if v != nil {
		_c.SetSurveyID(*v)
	}
	return _c
}

// SetSn sets the "sn" field.
func (_c *SurveyResponseCreate) SetSn(v string) *SurveyResponseCreate {
	_c.mutation.SetSn(v)
	return _c
}

// SetNillableSn sets the "sn" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableSn(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetSn(*v)
	}
	return _c
}

// SetRespondent sets the "respondent" field.
func (_c *SurveyResponseCreate) SetRespondent(v string) *SurveyResponseCreate {
	_c.mutation.SetRespondent(v)
	return _c
}

// SetNillableRespondent sets the "respondent" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableRespondent(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetRespondent(*v)
	}
	return _c
}

// SetRespondentPhone sets the "respondent_phone" field.
func (_c *SurveyResponseCreate) SetRespondentPhone(v string) *SurveyResponseCreate {
	_c.mutation.SetRespondentPhone(v)
	return _c
}

// SetNillableRespondentPhone sets the "respondent_phone" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableRespondentPhone(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetRespondentPhone(*v)
	}
	return _c
}

// SetResearcher sets the "researcher" field.
func (_c *SurveyResponseCreate) SetResearcher(v string) *SurveyResponseCreate {
	_c.mutation.SetResearcher(v)
	return _c
}

// SetNillableResearcher sets the "researcher" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableResearcher(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetResearcher(*v)
	}
	return _c
}

// SetResearcherPhone sets the "researcher_phone" field.
func (_c *SurveyResponseCreate) SetResearcherPhone(v string) *SurveyResponseCreate {
	_c.mutation.SetResearcherPhone(v)
	return _c
}

// SetNillableResearcherPhone sets the "researcher_phone" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableResearcherPhone(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetResearcherPhone(*v)
	}
	return _c
}

// SetPic sets the "pic" field.
func (_c *SurveyResponseCreate) SetPic(v []string) *SurveyResponseCreate {
	_c.mutation.SetPic(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *SurveyResponseCreate) SetIP(v string) *SurveyResponseCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableIP(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetLatitude sets the "latitude" field.
func (_c *SurveyResponseCreate) SetLatitude(v string) *SurveyResponseCreate {
	_c.mutation.SetLatitude(v)
	return _c
}

// SetNillableLatitude sets the "latitude" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableLatitude(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetLatitude(*v)
	}
	return _c
}

// SetLongitude sets the "longitude" field.
func (_c *SurveyResponseCreate) SetLongitude(v string) *SurveyResponseCreate {
	_c.mutation.SetLongitude(v)
	return _c
}

// SetNillableLongitude sets the "longitude" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableLongitude(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetLongitude(*v)
	}
	return _c
}

// SetDevice sets the "device" field.
func (_c *SurveyResponseCreate) SetDevice(v string) *SurveyResponseCreate {
	_c.mutation.SetDevice(v)
	return _c
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableDevice(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetDevice(*v)
	}
	return _c
}

// SetAudio sets the "audio" field.
func (_c *SurveyResponseCreate) SetAudio(v []string) *SurveyResponseCreate {
	_c.mutation.SetAudio(v)
	return _c
}

// SetArea sets the "area" field.
func (_c *SurveyResponseCreate) SetArea(v string) *SurveyResponseCreate {
	_c.mutation.SetArea(v)
	return _c
}

// SetNillableArea sets the "area" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableArea(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetArea(*v)
	}
	return _c
}

// SetCity sets the "city" field.
func (_c *SurveyResponseCreate) SetCity(v string) *SurveyResponseCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableCity(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetDistrict sets the "district" field.
func (_c *SurveyResponseCreate) SetDistrict(v string) *SurveyResponseCreate {
	_c.mutation.SetDistrict(v)
	return _c
}

// SetNillableDistrict sets the "district" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableDistrict(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetDistrict(*v)
	}
	return _c
}

// SetVillage sets the "village" field.
func (_c *SurveyResponseCreate) SetVillage(v string) *SurveyResponseCreate {
	_c.mutation.SetVillage(v)
	return _c
}

// SetNillableVillage sets the "village" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableVillage(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetVillage(*v)
	}
	return _c
}

// SetAddress sets the "address" field.
func (_c *SurveyResponseCreate) SetAddress(v string) *SurveyResponseCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableAddress(v *string) *SurveyResponseCreate {
	if v != nil {
		_c.SetAddress(*v)
	}
	return _c
}

// SetAnswersCount sets the "answers_count" field.
func (_c *SurveyResponseCreate) SetAnswersCount(v int64) *SurveyResponseCreate {
	_c.mutation.SetAnswersCount(v)
	return _c
}

// SetNillableAnswersCount sets the "answers_count" field if the given value is not nil.
func (_c *SurveyResponseCreate) SetNillableAnswersCount(v *int64) *SurveyResponseCreate {
	if v != nil {
		_c.SetAnswersCount(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SurveyResponseCreate) SetID(v int64) *SurveyResponseCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSurvey sets the "survey" edge to the Survey entity.
func (_c *SurveyResponseCreate) SetSurvey(v *Survey) *SurveyResponseCreate {
	return _c.SetSurveyID(v.ID)
}

// AddAnswerIDs adds the "answers" edge to the SurveyResponseAnswers entity by IDs.
func (_c *SurveyResponseCreate) AddAnswerIDs(ids ...int64) *SurveyResponseCreate {
	_c.mutation.AddAnswerIDs(ids...)
	return _c
}

// AddAnswers adds the "answers" edges to the SurveyResponseAnswers entity.
func (_c *SurveyResponseCreate) AddAnswers(v ...*SurveyResponseAnswers) *SurveyResponseCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAnswerIDs(ids...)
}

// Mutation returns the SurveyResponseMutation object of the builder.
func (_c *SurveyResponseCreate) Mutation() *SurveyResponseMutation {
	return _c.mutation
}

// Save creates the SurveyResponse in the database.
func (_c *SurveyResponseCreate) Save(ctx context.Context) (*SurveyResponse, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SurveyResponseCreate) SaveX(ctx context.Context) *SurveyResponse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SurveyResponseCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SurveyResponseCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SurveyResponseCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := surveyresponse.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := surveyresponse.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Delete(); !ok {
		v := surveyresponse.DefaultDelete
		_c.mutation.SetDelete(v)
	}
	if _, ok := _c.mutation.CreatedID(); !ok {
		v := surveyresponse.DefaultCreatedID
		_c.mutation.SetCreatedID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := surveyresponse.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SurveyID(); !ok {
		v := surveyresponse.DefaultSurveyID
		_c.mutation.SetSurveyID(v)
	}
	if _, ok := _c.mutation.Sn(); !ok {
		v := surveyresponse.DefaultSn
		_c.mutation.SetSn(v)
	}
	if _, ok := _c.mutation.Respondent(); !ok {
		v := surveyresponse.DefaultRespondent
		_c.mutation.SetRespondent(v)
	}
	if _, ok := _c.mutation.RespondentPhone(); !ok {
		v := surveyresponse.DefaultRespondentPhone
		_c.mutation.SetRespondentPhone(v)
	}
	if _, ok := _c.mutation.Researcher(); !ok {
		v := surveyresponse.DefaultResearcher
		_c.mutation.SetResearcher(v)
	}
	if _, ok := _c.mutation.ResearcherPhone(); !ok {
		v := surveyresponse.DefaultResearcherPhone
		_c.mutation.SetResearcherPhone(v)
	}
	if _, ok := _c.mutation.Pic(); !ok {
		v := surveyresponse.DefaultPic
		_c.mutation.SetPic(v)
	}
	if _, ok := _c.mutation.IP(); !ok {
		v := surveyresponse.DefaultIP
		_c.mutation.SetIP(v)
	}
	if _, ok := _c.mutation.Latitude(); !ok {
		v := surveyresponse.DefaultLatitude
		_c.mutation.SetLatitude(v)
	}
	if _, ok := _c.mutation.Longitude(); !ok {
		v := surveyresponse.DefaultLongitude
		_c.mutation.SetLongitude(v)
	}
	if _, ok := _c.mutation.Device(); !ok {
		v := surveyresponse.DefaultDevice
		_c.mutation.SetDevice(v)
	}
	if _, ok := _c.mutation.Audio(); !ok {
		v := surveyresponse.DefaultAudio
		_c.mutation.SetAudio(v)
	}
	if _, ok := _c.mutation.Area(); !ok {
		v := surveyresponse.DefaultArea
		_c.mutation.SetArea(v)
	}
	if _, ok := _c.mutation.City(); !ok {
		v := surveyresponse.DefaultCity
		_c.mutation.SetCity(v)
	}
	if _, ok := _c.mutation.District(); !ok {
		v := surveyresponse.DefaultDistrict
		_c.mutation.SetDistrict(v)
	}
	if _, ok := _c.mutation.Village(); !ok {
		v := surveyresponse.DefaultVillage
		_c.mutation.SetVillage(v)
	}
	if _, ok := _c.mutation.Address(); !ok {
		v := surveyresponse.DefaultAddress
		_c.mutation.SetAddress(v)
	}
	if _, ok := _c.mutation.AnswersCount(); !ok {
		v := surveyresponse.DefaultAnswersCount
		_c.mutation.SetAnswersCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SurveyResponseCreate) check() error {
	return nil
}

func (_c *SurveyResponseCreate) sqlSave(ctx context.Context) (*SurveyResponse, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SurveyResponseCreate) createSpec() (*SurveyResponse, *sqlgraph.CreateSpec) {
	var (
		_node = &SurveyResponse{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(surveyresponse.Table, sqlgraph.NewFieldSpec(surveyresponse.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(surveyresponse.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(surveyresponse.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Delete(); ok {
		_spec.SetField(surveyresponse.FieldDelete, field.TypeInt64, value)
		_node.Delete = value
	}
	if value, ok := _c.mutation.CreatedID(); ok {
		_spec.SetField(surveyresponse.FieldCreatedID, field.TypeInt64, value)
		_node.CreatedID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(surveyresponse.FieldStatus, field.TypeInt64, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Sn(); ok {
		_spec.SetField(surveyresponse.FieldSn, field.TypeString, value)
		_node.Sn = value
	}
	if value, ok := _c.mutation.Respondent(); ok {
		_spec.SetField(surveyresponse.FieldRespondent, field.TypeString, value)
		_node.Respondent = value
	}
	if value, ok := _c.mutation.RespondentPhone(); ok {
		_spec.SetField(surveyresponse.FieldRespondentPhone, field.TypeString, value)
		_node.RespondentPhone = value
	}
	if value, ok := _c.mutation.Researcher(); ok {
		_spec.SetField(surveyresponse.FieldResearcher, field.TypeString, value)
		_node.Researcher = value
	}
	if value, ok := _c.mutation.ResearcherPhone(); ok {
		_spec.SetField(surveyresponse.FieldResearcherPhone, field.TypeString, value)
		_node.ResearcherPhone = value
	}
	if value, ok := _c.mutation.Pic(); ok {
		_spec.SetField(surveyresponse.FieldPic, field.TypeJSON, value)
		_node.Pic = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(surveyresponse.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.Latitude(); ok {
		_spec.SetField(surveyresponse.FieldLatitude, field.TypeString, value)
		_node.Latitude = value
	}
	if value, ok := _c.mutation.Longitude(); ok {
		_spec.SetField(surveyresponse.FieldLongitude, field.TypeString, value)
		_node.Longitude = value
	}
	if value, ok := _c.mutation.Device(); ok {
		_spec.SetField(surveyresponse.FieldDevice, field.TypeString, value)
		_node.Device = value
	}
	if value, ok := _c.mutation.Audio(); ok {
		_spec.SetField(surveyresponse.FieldAudio, field.TypeJSON, value)
		_node.Audio = value
	}
	if value, ok := _c.mutation.Area(); ok {
		_spec.SetField(surveyresponse.FieldArea, field.TypeString, value)
		_node.Area = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(surveyresponse.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.District(); ok {
		_spec.SetField(surveyresponse.FieldDistrict, field.TypeString, value)
		_node.District = value
	}
	if value, ok := _c.mutation.Village(); ok {
		_spec.SetField(surveyresponse.FieldVillage, field.TypeString, value)
		_node.Village = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(surveyresponse.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.AnswersCount(); ok {
		_spec.SetField(surveyresponse.FieldAnswersCount, field.TypeInt64, value)
		_node.AnswersCount = value
	}
	if nodes := _c.mutation.SurveyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   surveyresponse.SurveyTable,
			Columns: []string{surveyresponse.SurveyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(survey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SurveyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   surveyresponse.AnswersTable,
			Columns: []string{surveyresponse.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyresponseanswers.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SurveyResponseCreateBulk is the builder for creating many SurveyResponse entities in bulk.
type SurveyResponseCreateBulk struct {
	config
	err      error
	builders []*SurveyResponseCreate
}

// Save creates the SurveyResponse entities in the database.
func (_c *SurveyResponseCreateBulk) Save(ctx context.Context) ([]*SurveyResponse, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SurveyResponse, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SurveyResponseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SurveyResponseCreateBulk) SaveX(ctx context.Context) []*SurveyResponse {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SurveyResponseCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SurveyResponseCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
