// Code generated by ent, DO NOT EDIT.

package ent

import (
	"kcers-survey/biz/dal/db/mysql/ent/api"
	"kcers-survey/biz/dal/db/mysql/ent/dictionary"
	"kcers-survey/biz/dal/db/mysql/ent/dictionarydetail"
	"kcers-survey/biz/dal/db/mysql/ent/logs"
	"kcers-survey/biz/dal/db/mysql/ent/menu"
	"kcers-survey/biz/dal/db/mysql/ent/menuparam"
	"kcers-survey/biz/dal/db/mysql/ent/role"
	"kcers-survey/biz/dal/db/mysql/ent/schema"
	"kcers-survey/biz/dal/db/mysql/ent/survey"
	"kcers-survey/biz/dal/db/mysql/ent/surveyquestion"
	"kcers-survey/biz/dal/db/mysql/ent/surveyquestionoptions"
	"kcers-survey/biz/dal/db/mysql/ent/surveyresponse"
	"kcers-survey/biz/dal/db/mysql/ent/surveyresponseanswers"
	"kcers-survey/biz/dal/db/mysql/ent/token"
	"kcers-survey/biz/dal/db/mysql/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apiMixin := schema.API{}.Mixin()
	apiMixinFields0 := apiMixin[0].Fields()
	_ = apiMixinFields0
	apiFields := schema.API{}.Fields()
	_ = apiFields
	// apiDescCreatedAt is the schema descriptor for created_at field.
	apiDescCreatedAt := apiMixinFields0[1].Descriptor()
	// api.DefaultCreatedAt holds the default value on creation for the created_at field.
	api.DefaultCreatedAt = apiDescCreatedAt.Default.(func() time.Time)
	// apiDescUpdatedAt is the schema descriptor for updated_at field.
	apiDescUpdatedAt := apiMixinFields0[2].Descriptor()
	// api.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	api.DefaultUpdatedAt = apiDescUpdatedAt.Default.(func() time.Time)
	// api.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	api.UpdateDefaultUpdatedAt = apiDescUpdatedAt.UpdateDefault.(func() time.Time)
	// apiDescDelete is the schema descriptor for delete field.
	apiDescDelete := apiMixinFields0[3].Descriptor()
	// api.DefaultDelete holds the default value on creation for the delete field.
	api.DefaultDelete = apiDescDelete.Default.(int64)
	// apiDescCreatedID is the schema descriptor for created_id field.
	apiDescCreatedID := apiMixinFields0[4].Descriptor()
	// api.DefaultCreatedID holds the default value on creation for the created_id field.
	api.DefaultCreatedID = apiDescCreatedID.Default.(int64)
	// apiDescMethod is the schema descriptor for method field.
	apiDescMethod := apiFields[4].Descriptor()
	// api.DefaultMethod holds the default value on creation for the method field.
	api.DefaultMethod = apiDescMethod.Default.(string)
	dictionaryMixin := schema.Dictionary{}.Mixin()
	dictionaryMixinFields0 := dictionaryMixin[0].Fields()
	_ = dictionaryMixinFields0
	dictionaryMixinFields1 := dictionaryMixin[1].Fields()
	_ = dictionaryMixinFields1
	dictionaryFields := schema.Dictionary{}.Fields()
	_ = dictionaryFields
	// dictionaryDescCreatedAt is the schema descriptor for created_at field.
	dictionaryDescCreatedAt := dictionaryMixinFields0[1].Descriptor()
	// dictionary.DefaultCreatedAt holds the default value on creation for the created_at field.
	dictionary.DefaultCreatedAt = dictionaryDescCreatedAt.Default.(func() time.Time)
	// dictionaryDescUpdatedAt is the schema descriptor for updated_at field.
	dictionaryDescUpdatedAt := dictionaryMixinFields0[2].Descriptor()
	// dictionary.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dictionary.DefaultUpdatedAt = dictionaryDescUpdatedAt.Default.(func() time.Time)
	// dictionary.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dictionary.UpdateDefaultUpdatedAt = dictionaryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dictionaryDescDelete is the schema descriptor for delete field.
	dictionaryDescDelete := dictionaryMixinFields0[3].Descriptor()
	// dictionary.DefaultDelete holds the default value on creation for the delete field.
	dictionary.DefaultDelete = dictionaryDescDelete.Default.(int64)
	// dictionaryDescCreatedID is the schema descriptor for created_id field.
	dictionaryDescCreatedID := dictionaryMixinFields0[4].Descriptor()
	// dictionary.DefaultCreatedID holds the default value on creation for the created_id field.
	dictionary.DefaultCreatedID = dictionaryDescCreatedID.Default.(int64)
	// dictionaryDescStatus is the schema descriptor for status field.
	dictionaryDescStatus := dictionaryMixinFields1[0].Descriptor()
	// dictionary.DefaultStatus holds the default value on creation for the status field.
	dictionary.DefaultStatus = dictionaryDescStatus.Default.(int64)
	dictionarydetailMixin := schema.DictionaryDetail{}.Mixin()
	dictionarydetailMixinFields0 := dictionarydetailMixin[0].Fields()
	_ = dictionarydetailMixinFields0
	dictionarydetailMixinFields1 := dictionarydetailMixin[1].Fields()
	_ = dictionarydetailMixinFields1
	dictionarydetailFields := schema.DictionaryDetail{}.Fields()
	_ = dictionarydetailFields
	// dictionarydetailDescCreatedAt is the schema descriptor for created_at field.
	dictionarydetailDescCreatedAt := dictionarydetailMixinFields0[1].Descriptor()
	// dictionarydetail.DefaultCreatedAt holds the default value on creation for the created_at field.
	dictionarydetail.DefaultCreatedAt = dictionarydetailDescCreatedAt.Default.(func() time.Time)
	// dictionarydetailDescUpdatedAt is the schema descriptor for updated_at field.
	dictionarydetailDescUpdatedAt := dictionarydetailMixinFields0[2].Descriptor()
	// dictionarydetail.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dictionarydetail.DefaultUpdatedAt = dictionarydetailDescUpdatedAt.Default.(func() time.Time)
	// dictionarydetail.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dictionarydetail.UpdateDefaultUpdatedAt = dictionarydetailDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dictionarydetailDescDelete is the schema descriptor for delete field.
	dictionarydetailDescDelete := dictionarydetailMixinFields0[3].Descriptor()
	// dictionarydetail.DefaultDelete holds the default value on creation for the delete field.
	dictionarydetail.DefaultDelete = dictionarydetailDescDelete.Default.(int64)
	// dictionarydetailDescCreatedID is the schema descriptor for created_id field.
	dictionarydetailDescCreatedID := dictionarydetailMixinFields0[4].Descriptor()
	// dictionarydetail.DefaultCreatedID holds the default value on creation for the created_id field.
	dictionarydetail.DefaultCreatedID = dictionarydetailDescCreatedID.Default.(int64)
	// dictionarydetailDescStatus is the schema descriptor for status field.
	dictionarydetailDescStatus := dictionarydetailMixinFields1[0].Descriptor()
	// dictionarydetail.DefaultStatus holds the default value on creation for the status field.
	dictionarydetail.DefaultStatus = dictionarydetailDescStatus.Default.(int64)
	logsMixin := schema.Logs{}.Mixin()
	logsMixinFields0 := logsMixin[0].Fields()
	_ = logsMixinFields0
	logsFields := schema.Logs{}.Fields()
	_ = logsFields
	// logsDescCreatedAt is the schema descriptor for created_at field.
	logsDescCreatedAt := logsMixinFields0[1].Descriptor()
	// logs.DefaultCreatedAt holds the default value on creation for the created_at field.
	logs.DefaultCreatedAt = logsDescCreatedAt.Default.(func() time.Time)
	// logsDescUpdatedAt is the schema descriptor for updated_at field.
	logsDescUpdatedAt := logsMixinFields0[2].Descriptor()
	// logs.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	logs.DefaultUpdatedAt = logsDescUpdatedAt.Default.(func() time.Time)
	// logs.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	logs.UpdateDefaultUpdatedAt = logsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// logsDescDelete is the schema descriptor for delete field.
	logsDescDelete := logsMixinFields0[3].Descriptor()
	// logs.DefaultDelete holds the default value on creation for the delete field.
	logs.DefaultDelete = logsDescDelete.Default.(int64)
	// logsDescCreatedID is the schema descriptor for created_id field.
	logsDescCreatedID := logsMixinFields0[4].Descriptor()
	// logs.DefaultCreatedID holds the default value on creation for the created_id field.
	logs.DefaultCreatedID = logsDescCreatedID.Default.(int64)
	menuMixin := schema.Menu{}.Mixin()
	menuMixinFields0 := menuMixin[0].Fields()
	_ = menuMixinFields0
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreatedAt is the schema descriptor for created_at field.
	menuDescCreatedAt := menuMixinFields0[1].Descriptor()
	// menu.DefaultCreatedAt holds the default value on creation for the created_at field.
	menu.DefaultCreatedAt = menuDescCreatedAt.Default.(func() time.Time)
	// menuDescUpdatedAt is the schema descriptor for updated_at field.
	menuDescUpdatedAt := menuMixinFields0[2].Descriptor()
	// menu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menu.DefaultUpdatedAt = menuDescUpdatedAt.Default.(func() time.Time)
	// menu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menu.UpdateDefaultUpdatedAt = menuDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menuDescDelete is the schema descriptor for delete field.
	menuDescDelete := menuMixinFields0[3].Descriptor()
	// menu.DefaultDelete holds the default value on creation for the delete field.
	menu.DefaultDelete = menuDescDelete.Default.(int64)
	// menuDescCreatedID is the schema descriptor for created_id field.
	menuDescCreatedID := menuMixinFields0[4].Descriptor()
	// menu.DefaultCreatedID holds the default value on creation for the created_id field.
	menu.DefaultCreatedID = menuDescCreatedID.Default.(int64)
	// menuDescPath is the schema descriptor for path field.
	menuDescPath := menuFields[1].Descriptor()
	// menu.DefaultPath holds the default value on creation for the path field.
	menu.DefaultPath = menuDescPath.Default.(string)
	// menuDescOrderNo is the schema descriptor for order_no field.
	menuDescOrderNo := menuFields[3].Descriptor()
	// menu.DefaultOrderNo holds the default value on creation for the order_no field.
	menu.DefaultOrderNo = menuDescOrderNo.Default.(int64)
	// menuDescDisabled is the schema descriptor for disabled field.
	menuDescDisabled := menuFields[4].Descriptor()
	// menu.DefaultDisabled holds the default value on creation for the disabled field.
	menu.DefaultDisabled = menuDescDisabled.Default.(int64)
	// menuDescIgnore is the schema descriptor for ignore field.
	menuDescIgnore := menuFields[5].Descriptor()
	// menu.DefaultIgnore holds the default value on creation for the ignore field.
	menu.DefaultIgnore = menuDescIgnore.Default.(bool)
	menuparamMixin := schema.MenuParam{}.Mixin()
	menuparamMixinFields0 := menuparamMixin[0].Fields()
	_ = menuparamMixinFields0
	menuparamFields := schema.MenuParam{}.Fields()
	_ = menuparamFields
	// menuparamDescCreatedAt is the schema descriptor for created_at field.
	menuparamDescCreatedAt := menuparamMixinFields0[1].Descriptor()
	// menuparam.DefaultCreatedAt holds the default value on creation for the created_at field.
	menuparam.DefaultCreatedAt = menuparamDescCreatedAt.Default.(func() time.Time)
	// menuparamDescUpdatedAt is the schema descriptor for updated_at field.
	menuparamDescUpdatedAt := menuparamMixinFields0[2].Descriptor()
	// menuparam.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menuparam.DefaultUpdatedAt = menuparamDescUpdatedAt.Default.(func() time.Time)
	// menuparam.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menuparam.UpdateDefaultUpdatedAt = menuparamDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menuparamDescDelete is the schema descriptor for delete field.
	menuparamDescDelete := menuparamMixinFields0[3].Descriptor()
	// menuparam.DefaultDelete holds the default value on creation for the delete field.
	menuparam.DefaultDelete = menuparamDescDelete.Default.(int64)
	// menuparamDescCreatedID is the schema descriptor for created_id field.
	menuparamDescCreatedID := menuparamMixinFields0[4].Descriptor()
	// menuparam.DefaultCreatedID holds the default value on creation for the created_id field.
	menuparam.DefaultCreatedID = menuparamDescCreatedID.Default.(int64)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleMixinFields1 := roleMixin[1].Fields()
	_ = roleMixinFields1
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[2].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescDelete is the schema descriptor for delete field.
	roleDescDelete := roleMixinFields0[3].Descriptor()
	// role.DefaultDelete holds the default value on creation for the delete field.
	role.DefaultDelete = roleDescDelete.Default.(int64)
	// roleDescCreatedID is the schema descriptor for created_id field.
	roleDescCreatedID := roleMixinFields0[4].Descriptor()
	// role.DefaultCreatedID holds the default value on creation for the created_id field.
	role.DefaultCreatedID = roleDescCreatedID.Default.(int64)
	// roleDescStatus is the schema descriptor for status field.
	roleDescStatus := roleMixinFields1[0].Descriptor()
	// role.DefaultStatus holds the default value on creation for the status field.
	role.DefaultStatus = roleDescStatus.Default.(int64)
	// roleDescDefaultRouter is the schema descriptor for default_router field.
	roleDescDefaultRouter := roleFields[2].Descriptor()
	// role.DefaultDefaultRouter holds the default value on creation for the default_router field.
	role.DefaultDefaultRouter = roleDescDefaultRouter.Default.(string)
	// roleDescRemark is the schema descriptor for remark field.
	roleDescRemark := roleFields[3].Descriptor()
	// role.DefaultRemark holds the default value on creation for the remark field.
	role.DefaultRemark = roleDescRemark.Default.(string)
	// roleDescOrderNo is the schema descriptor for order_no field.
	roleDescOrderNo := roleFields[4].Descriptor()
	// role.DefaultOrderNo holds the default value on creation for the order_no field.
	role.DefaultOrderNo = roleDescOrderNo.Default.(int64)
	// roleDescApis is the schema descriptor for apis field.
	roleDescApis := roleFields[5].Descriptor()
	// role.DefaultApis holds the default value on creation for the apis field.
	role.DefaultApis = roleDescApis.Default.([]int)
	// roleDescVenueID is the schema descriptor for venue_id field.
	roleDescVenueID := roleFields[6].Descriptor()
	// role.DefaultVenueID holds the default value on creation for the venue_id field.
	role.DefaultVenueID = roleDescVenueID.Default.(int64)
	surveyMixin := schema.Survey{}.Mixin()
	surveyMixinFields0 := surveyMixin[0].Fields()
	_ = surveyMixinFields0
	surveyMixinFields1 := surveyMixin[1].Fields()
	_ = surveyMixinFields1
	surveyFields := schema.Survey{}.Fields()
	_ = surveyFields
	// surveyDescCreatedAt is the schema descriptor for created_at field.
	surveyDescCreatedAt := surveyMixinFields0[1].Descriptor()
	// survey.DefaultCreatedAt holds the default value on creation for the created_at field.
	survey.DefaultCreatedAt = surveyDescCreatedAt.Default.(func() time.Time)
	// surveyDescUpdatedAt is the schema descriptor for updated_at field.
	surveyDescUpdatedAt := surveyMixinFields0[2].Descriptor()
	// survey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	survey.DefaultUpdatedAt = surveyDescUpdatedAt.Default.(func() time.Time)
	// survey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	survey.UpdateDefaultUpdatedAt = surveyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// surveyDescDelete is the schema descriptor for delete field.
	surveyDescDelete := surveyMixinFields0[3].Descriptor()
	// survey.DefaultDelete holds the default value on creation for the delete field.
	survey.DefaultDelete = surveyDescDelete.Default.(int64)
	// surveyDescCreatedID is the schema descriptor for created_id field.
	surveyDescCreatedID := surveyMixinFields0[4].Descriptor()
	// survey.DefaultCreatedID holds the default value on creation for the created_id field.
	survey.DefaultCreatedID = surveyDescCreatedID.Default.(int64)
	// surveyDescStatus is the schema descriptor for status field.
	surveyDescStatus := surveyMixinFields1[0].Descriptor()
	// survey.DefaultStatus holds the default value on creation for the status field.
	survey.DefaultStatus = surveyDescStatus.Default.(int64)
	// surveyDescTitle is the schema descriptor for title field.
	surveyDescTitle := surveyFields[0].Descriptor()
	// survey.DefaultTitle holds the default value on creation for the title field.
	survey.DefaultTitle = surveyDescTitle.Default.(string)
	// surveyDescPic is the schema descriptor for pic field.
	surveyDescPic := surveyFields[1].Descriptor()
	// survey.DefaultPic holds the default value on creation for the pic field.
	survey.DefaultPic = surveyDescPic.Default.(string)
	// surveyDescDesc is the schema descriptor for desc field.
	surveyDescDesc := surveyFields[2].Descriptor()
	// survey.DefaultDesc holds the default value on creation for the desc field.
	survey.DefaultDesc = surveyDescDesc.Default.(string)
	surveyquestionMixin := schema.SurveyQuestion{}.Mixin()
	surveyquestionMixinFields0 := surveyquestionMixin[0].Fields()
	_ = surveyquestionMixinFields0
	surveyquestionMixinFields1 := surveyquestionMixin[1].Fields()
	_ = surveyquestionMixinFields1
	surveyquestionFields := schema.SurveyQuestion{}.Fields()
	_ = surveyquestionFields
	// surveyquestionDescCreatedAt is the schema descriptor for created_at field.
	surveyquestionDescCreatedAt := surveyquestionMixinFields0[1].Descriptor()
	// surveyquestion.DefaultCreatedAt holds the default value on creation for the created_at field.
	surveyquestion.DefaultCreatedAt = surveyquestionDescCreatedAt.Default.(func() time.Time)
	// surveyquestionDescUpdatedAt is the schema descriptor for updated_at field.
	surveyquestionDescUpdatedAt := surveyquestionMixinFields0[2].Descriptor()
	// surveyquestion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	surveyquestion.DefaultUpdatedAt = surveyquestionDescUpdatedAt.Default.(func() time.Time)
	// surveyquestion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	surveyquestion.UpdateDefaultUpdatedAt = surveyquestionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// surveyquestionDescDelete is the schema descriptor for delete field.
	surveyquestionDescDelete := surveyquestionMixinFields0[3].Descriptor()
	// surveyquestion.DefaultDelete holds the default value on creation for the delete field.
	surveyquestion.DefaultDelete = surveyquestionDescDelete.Default.(int64)
	// surveyquestionDescCreatedID is the schema descriptor for created_id field.
	surveyquestionDescCreatedID := surveyquestionMixinFields0[4].Descriptor()
	// surveyquestion.DefaultCreatedID holds the default value on creation for the created_id field.
	surveyquestion.DefaultCreatedID = surveyquestionDescCreatedID.Default.(int64)
	// surveyquestionDescStatus is the schema descriptor for status field.
	surveyquestionDescStatus := surveyquestionMixinFields1[0].Descriptor()
	// surveyquestion.DefaultStatus holds the default value on creation for the status field.
	surveyquestion.DefaultStatus = surveyquestionDescStatus.Default.(int64)
	// surveyquestionDescSurveyID is the schema descriptor for survey_id field.
	surveyquestionDescSurveyID := surveyquestionFields[0].Descriptor()
	// surveyquestion.DefaultSurveyID holds the default value on creation for the survey_id field.
	surveyquestion.DefaultSurveyID = surveyquestionDescSurveyID.Default.(int64)
	// surveyquestionDescParentID is the schema descriptor for parent_id field.
	surveyquestionDescParentID := surveyquestionFields[1].Descriptor()
	// surveyquestion.DefaultParentID holds the default value on creation for the parent_id field.
	surveyquestion.DefaultParentID = surveyquestionDescParentID.Default.(int64)
	// surveyquestionDescContent is the schema descriptor for content field.
	surveyquestionDescContent := surveyquestionFields[2].Descriptor()
	// surveyquestion.DefaultContent holds the default value on creation for the content field.
	surveyquestion.DefaultContent = surveyquestionDescContent.Default.(string)
	// surveyquestionDescType is the schema descriptor for type field.
	surveyquestionDescType := surveyquestionFields[3].Descriptor()
	// surveyquestion.DefaultType holds the default value on creation for the type field.
	surveyquestion.DefaultType = surveyquestionDescType.Default.(string)
	// surveyquestionDescSort is the schema descriptor for sort field.
	surveyquestionDescSort := surveyquestionFields[4].Descriptor()
	// surveyquestion.DefaultSort holds the default value on creation for the sort field.
	surveyquestion.DefaultSort = surveyquestionDescSort.Default.(int64)
	// surveyquestionDescTo is the schema descriptor for to field.
	surveyquestionDescTo := surveyquestionFields[5].Descriptor()
	// surveyquestion.DefaultTo holds the default value on creation for the to field.
	surveyquestion.DefaultTo = surveyquestionDescTo.Default.(int64)
	// surveyquestionDescRequired is the schema descriptor for required field.
	surveyquestionDescRequired := surveyquestionFields[6].Descriptor()
	// surveyquestion.DefaultRequired holds the default value on creation for the required field.
	surveyquestion.DefaultRequired = surveyquestionDescRequired.Default.(int64)
	surveyquestionoptionsMixin := schema.SurveyQuestionOptions{}.Mixin()
	surveyquestionoptionsMixinFields0 := surveyquestionoptionsMixin[0].Fields()
	_ = surveyquestionoptionsMixinFields0
	surveyquestionoptionsMixinFields1 := surveyquestionoptionsMixin[1].Fields()
	_ = surveyquestionoptionsMixinFields1
	surveyquestionoptionsFields := schema.SurveyQuestionOptions{}.Fields()
	_ = surveyquestionoptionsFields
	// surveyquestionoptionsDescCreatedAt is the schema descriptor for created_at field.
	surveyquestionoptionsDescCreatedAt := surveyquestionoptionsMixinFields0[1].Descriptor()
	// surveyquestionoptions.DefaultCreatedAt holds the default value on creation for the created_at field.
	surveyquestionoptions.DefaultCreatedAt = surveyquestionoptionsDescCreatedAt.Default.(func() time.Time)
	// surveyquestionoptionsDescUpdatedAt is the schema descriptor for updated_at field.
	surveyquestionoptionsDescUpdatedAt := surveyquestionoptionsMixinFields0[2].Descriptor()
	// surveyquestionoptions.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	surveyquestionoptions.DefaultUpdatedAt = surveyquestionoptionsDescUpdatedAt.Default.(func() time.Time)
	// surveyquestionoptions.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	surveyquestionoptions.UpdateDefaultUpdatedAt = surveyquestionoptionsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// surveyquestionoptionsDescDelete is the schema descriptor for delete field.
	surveyquestionoptionsDescDelete := surveyquestionoptionsMixinFields0[3].Descriptor()
	// surveyquestionoptions.DefaultDelete holds the default value on creation for the delete field.
	surveyquestionoptions.DefaultDelete = surveyquestionoptionsDescDelete.Default.(int64)
	// surveyquestionoptionsDescCreatedID is the schema descriptor for created_id field.
	surveyquestionoptionsDescCreatedID := surveyquestionoptionsMixinFields0[4].Descriptor()
	// surveyquestionoptions.DefaultCreatedID holds the default value on creation for the created_id field.
	surveyquestionoptions.DefaultCreatedID = surveyquestionoptionsDescCreatedID.Default.(int64)
	// surveyquestionoptionsDescStatus is the schema descriptor for status field.
	surveyquestionoptionsDescStatus := surveyquestionoptionsMixinFields1[0].Descriptor()
	// surveyquestionoptions.DefaultStatus holds the default value on creation for the status field.
	surveyquestionoptions.DefaultStatus = surveyquestionoptionsDescStatus.Default.(int64)
	// surveyquestionoptionsDescSurveyQuestionID is the schema descriptor for survey_question_id field.
	surveyquestionoptionsDescSurveyQuestionID := surveyquestionoptionsFields[0].Descriptor()
	// surveyquestionoptions.DefaultSurveyQuestionID holds the default value on creation for the survey_question_id field.
	surveyquestionoptions.DefaultSurveyQuestionID = surveyquestionoptionsDescSurveyQuestionID.Default.(int64)
	// surveyquestionoptionsDescSerial is the schema descriptor for serial field.
	surveyquestionoptionsDescSerial := surveyquestionoptionsFields[1].Descriptor()
	// surveyquestionoptions.DefaultSerial holds the default value on creation for the serial field.
	surveyquestionoptions.DefaultSerial = surveyquestionoptionsDescSerial.Default.(string)
	// surveyquestionoptionsDescContent is the schema descriptor for content field.
	surveyquestionoptionsDescContent := surveyquestionoptionsFields[2].Descriptor()
	// surveyquestionoptions.DefaultContent holds the default value on creation for the content field.
	surveyquestionoptions.DefaultContent = surveyquestionoptionsDescContent.Default.(string)
	surveyresponseMixin := schema.SurveyResponse{}.Mixin()
	surveyresponseMixinFields0 := surveyresponseMixin[0].Fields()
	_ = surveyresponseMixinFields0
	surveyresponseMixinFields1 := surveyresponseMixin[1].Fields()
	_ = surveyresponseMixinFields1
	surveyresponseFields := schema.SurveyResponse{}.Fields()
	_ = surveyresponseFields
	// surveyresponseDescCreatedAt is the schema descriptor for created_at field.
	surveyresponseDescCreatedAt := surveyresponseMixinFields0[1].Descriptor()
	// surveyresponse.DefaultCreatedAt holds the default value on creation for the created_at field.
	surveyresponse.DefaultCreatedAt = surveyresponseDescCreatedAt.Default.(func() time.Time)
	// surveyresponseDescUpdatedAt is the schema descriptor for updated_at field.
	surveyresponseDescUpdatedAt := surveyresponseMixinFields0[2].Descriptor()
	// surveyresponse.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	surveyresponse.DefaultUpdatedAt = surveyresponseDescUpdatedAt.Default.(func() time.Time)
	// surveyresponse.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	surveyresponse.UpdateDefaultUpdatedAt = surveyresponseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// surveyresponseDescDelete is the schema descriptor for delete field.
	surveyresponseDescDelete := surveyresponseMixinFields0[3].Descriptor()
	// surveyresponse.DefaultDelete holds the default value on creation for the delete field.
	surveyresponse.DefaultDelete = surveyresponseDescDelete.Default.(int64)
	// surveyresponseDescCreatedID is the schema descriptor for created_id field.
	surveyresponseDescCreatedID := surveyresponseMixinFields0[4].Descriptor()
	// surveyresponse.DefaultCreatedID holds the default value on creation for the created_id field.
	surveyresponse.DefaultCreatedID = surveyresponseDescCreatedID.Default.(int64)
	// surveyresponseDescStatus is the schema descriptor for status field.
	surveyresponseDescStatus := surveyresponseMixinFields1[0].Descriptor()
	// surveyresponse.DefaultStatus holds the default value on creation for the status field.
	surveyresponse.DefaultStatus = surveyresponseDescStatus.Default.(int64)
	// surveyresponseDescSurveyID is the schema descriptor for survey_id field.
	surveyresponseDescSurveyID := surveyresponseFields[0].Descriptor()
	// surveyresponse.DefaultSurveyID holds the default value on creation for the survey_id field.
	surveyresponse.DefaultSurveyID = surveyresponseDescSurveyID.Default.(int64)
	// surveyresponseDescRespondent is the schema descriptor for respondent field.
	surveyresponseDescRespondent := surveyresponseFields[1].Descriptor()
	// surveyresponse.DefaultRespondent holds the default value on creation for the respondent field.
	surveyresponse.DefaultRespondent = surveyresponseDescRespondent.Default.(string)
	// surveyresponseDescIP is the schema descriptor for ip field.
	surveyresponseDescIP := surveyresponseFields[2].Descriptor()
	// surveyresponse.DefaultIP holds the default value on creation for the ip field.
	surveyresponse.DefaultIP = surveyresponseDescIP.Default.(string)
	// surveyresponseDescMap is the schema descriptor for map field.
	surveyresponseDescMap := surveyresponseFields[3].Descriptor()
	// surveyresponse.DefaultMap holds the default value on creation for the map field.
	surveyresponse.DefaultMap = surveyresponseDescMap.Default.(string)
	// surveyresponseDescDevice is the schema descriptor for device field.
	surveyresponseDescDevice := surveyresponseFields[4].Descriptor()
	// surveyresponse.DefaultDevice holds the default value on creation for the device field.
	surveyresponse.DefaultDevice = surveyresponseDescDevice.Default.(string)
	// surveyresponseDescAudio is the schema descriptor for audio field.
	surveyresponseDescAudio := surveyresponseFields[5].Descriptor()
	// surveyresponse.DefaultAudio holds the default value on creation for the audio field.
	surveyresponse.DefaultAudio = surveyresponseDescAudio.Default.(string)
	surveyresponseanswersMixin := schema.SurveyResponseAnswers{}.Mixin()
	surveyresponseanswersMixinFields0 := surveyresponseanswersMixin[0].Fields()
	_ = surveyresponseanswersMixinFields0
	surveyresponseanswersMixinFields1 := surveyresponseanswersMixin[1].Fields()
	_ = surveyresponseanswersMixinFields1
	surveyresponseanswersFields := schema.SurveyResponseAnswers{}.Fields()
	_ = surveyresponseanswersFields
	// surveyresponseanswersDescCreatedAt is the schema descriptor for created_at field.
	surveyresponseanswersDescCreatedAt := surveyresponseanswersMixinFields0[1].Descriptor()
	// surveyresponseanswers.DefaultCreatedAt holds the default value on creation for the created_at field.
	surveyresponseanswers.DefaultCreatedAt = surveyresponseanswersDescCreatedAt.Default.(func() time.Time)
	// surveyresponseanswersDescUpdatedAt is the schema descriptor for updated_at field.
	surveyresponseanswersDescUpdatedAt := surveyresponseanswersMixinFields0[2].Descriptor()
	// surveyresponseanswers.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	surveyresponseanswers.DefaultUpdatedAt = surveyresponseanswersDescUpdatedAt.Default.(func() time.Time)
	// surveyresponseanswers.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	surveyresponseanswers.UpdateDefaultUpdatedAt = surveyresponseanswersDescUpdatedAt.UpdateDefault.(func() time.Time)
	// surveyresponseanswersDescDelete is the schema descriptor for delete field.
	surveyresponseanswersDescDelete := surveyresponseanswersMixinFields0[3].Descriptor()
	// surveyresponseanswers.DefaultDelete holds the default value on creation for the delete field.
	surveyresponseanswers.DefaultDelete = surveyresponseanswersDescDelete.Default.(int64)
	// surveyresponseanswersDescCreatedID is the schema descriptor for created_id field.
	surveyresponseanswersDescCreatedID := surveyresponseanswersMixinFields0[4].Descriptor()
	// surveyresponseanswers.DefaultCreatedID holds the default value on creation for the created_id field.
	surveyresponseanswers.DefaultCreatedID = surveyresponseanswersDescCreatedID.Default.(int64)
	// surveyresponseanswersDescStatus is the schema descriptor for status field.
	surveyresponseanswersDescStatus := surveyresponseanswersMixinFields1[0].Descriptor()
	// surveyresponseanswers.DefaultStatus holds the default value on creation for the status field.
	surveyresponseanswers.DefaultStatus = surveyresponseanswersDescStatus.Default.(int64)
	// surveyresponseanswersDescSurveyID is the schema descriptor for survey_id field.
	surveyresponseanswersDescSurveyID := surveyresponseanswersFields[0].Descriptor()
	// surveyresponseanswers.DefaultSurveyID holds the default value on creation for the survey_id field.
	surveyresponseanswers.DefaultSurveyID = surveyresponseanswersDescSurveyID.Default.(int64)
	// surveyresponseanswersDescSurveyResponseID is the schema descriptor for survey_response_id field.
	surveyresponseanswersDescSurveyResponseID := surveyresponseanswersFields[1].Descriptor()
	// surveyresponseanswers.DefaultSurveyResponseID holds the default value on creation for the survey_response_id field.
	surveyresponseanswers.DefaultSurveyResponseID = surveyresponseanswersDescSurveyResponseID.Default.(int64)
	// surveyresponseanswersDescSurveyQuestionID is the schema descriptor for survey_question_id field.
	surveyresponseanswersDescSurveyQuestionID := surveyresponseanswersFields[2].Descriptor()
	// surveyresponseanswers.DefaultSurveyQuestionID holds the default value on creation for the survey_question_id field.
	surveyresponseanswers.DefaultSurveyQuestionID = surveyresponseanswersDescSurveyQuestionID.Default.(int64)
	// surveyresponseanswersDescAnswerValue is the schema descriptor for answer_value field.
	surveyresponseanswersDescAnswerValue := surveyresponseanswersFields[4].Descriptor()
	// surveyresponseanswers.DefaultAnswerValue holds the default value on creation for the answer_value field.
	surveyresponseanswers.DefaultAnswerValue = surveyresponseanswersDescAnswerValue.Default.(int64)
	tokenMixin := schema.Token{}.Mixin()
	tokenMixinFields0 := tokenMixin[0].Fields()
	_ = tokenMixinFields0
	tokenFields := schema.Token{}.Fields()
	_ = tokenFields
	// tokenDescCreatedAt is the schema descriptor for created_at field.
	tokenDescCreatedAt := tokenMixinFields0[1].Descriptor()
	// token.DefaultCreatedAt holds the default value on creation for the created_at field.
	token.DefaultCreatedAt = tokenDescCreatedAt.Default.(func() time.Time)
	// tokenDescUpdatedAt is the schema descriptor for updated_at field.
	tokenDescUpdatedAt := tokenMixinFields0[2].Descriptor()
	// token.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	token.DefaultUpdatedAt = tokenDescUpdatedAt.Default.(func() time.Time)
	// token.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	token.UpdateDefaultUpdatedAt = tokenDescUpdatedAt.UpdateDefault.(func() time.Time)
	// tokenDescDelete is the schema descriptor for delete field.
	tokenDescDelete := tokenMixinFields0[3].Descriptor()
	// token.DefaultDelete holds the default value on creation for the delete field.
	token.DefaultDelete = tokenDescDelete.Default.(int64)
	// tokenDescCreatedID is the schema descriptor for created_id field.
	tokenDescCreatedID := tokenMixinFields0[4].Descriptor()
	// token.DefaultCreatedID holds the default value on creation for the created_id field.
	token.DefaultCreatedID = tokenDescCreatedID.Default.(int64)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescDelete is the schema descriptor for delete field.
	userDescDelete := userMixinFields0[3].Descriptor()
	// user.DefaultDelete holds the default value on creation for the delete field.
	user.DefaultDelete = userDescDelete.Default.(int64)
	// userDescCreatedID is the schema descriptor for created_id field.
	userDescCreatedID := userMixinFields0[4].Descriptor()
	// user.DefaultCreatedID holds the default value on creation for the created_id field.
	user.DefaultCreatedID = userDescCreatedID.Default.(int64)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userMixinFields1[0].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int64)
	// userDescGender is the schema descriptor for gender field.
	userDescGender := userFields[2].Descriptor()
	// user.DefaultGender holds the default value on creation for the gender field.
	user.DefaultGender = userDescGender.Default.(int64)
	// userDescJobTime is the schema descriptor for job_time field.
	userDescJobTime := userFields[6].Descriptor()
	// user.DefaultJobTime holds the default value on creation for the job_time field.
	user.DefaultJobTime = userDescJobTime.Default.(int64)
	// userDescSideMode is the schema descriptor for side_mode field.
	userDescSideMode := userFields[8].Descriptor()
	// user.DefaultSideMode holds the default value on creation for the side_mode field.
	user.DefaultSideMode = userDescSideMode.Default.(string)
	// userDescBaseColor is the schema descriptor for base_color field.
	userDescBaseColor := userFields[9].Descriptor()
	// user.DefaultBaseColor holds the default value on creation for the base_color field.
	user.DefaultBaseColor = userDescBaseColor.Default.(string)
	// userDescActiveColor is the schema descriptor for active_color field.
	userDescActiveColor := userFields[10].Descriptor()
	// user.DefaultActiveColor holds the default value on creation for the active_color field.
	user.DefaultActiveColor = userDescActiveColor.Default.(string)
}
