// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"kcers-survey/biz/dal/db/mysql/ent/survey"
	"kcers-survey/biz/dal/db/mysql/ent/surveyquestion"
	"kcers-survey/biz/dal/db/mysql/ent/surveyresponseanswers"
	"kcers-survey/idl_gen/model/service"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SurveyQuestionCreate is the builder for creating a SurveyQuestion entity.
type SurveyQuestionCreate struct {
	config
	mutation *SurveyQuestionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SurveyQuestionCreate) SetCreatedAt(v time.Time) *SurveyQuestionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableCreatedAt(v *time.Time) *SurveyQuestionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SurveyQuestionCreate) SetUpdatedAt(v time.Time) *SurveyQuestionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableUpdatedAt(v *time.Time) *SurveyQuestionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDelete sets the "delete" field.
func (_c *SurveyQuestionCreate) SetDelete(v int64) *SurveyQuestionCreate {
	_c.mutation.SetDelete(v)
	return _c
}

// SetNillableDelete sets the "delete" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableDelete(v *int64) *SurveyQuestionCreate {
	if v != nil {
		_c.SetDelete(*v)
	}
	return _c
}

// SetCreatedID sets the "created_id" field.
func (_c *SurveyQuestionCreate) SetCreatedID(v int64) *SurveyQuestionCreate {
	_c.mutation.SetCreatedID(v)
	return _c
}

// SetNillableCreatedID sets the "created_id" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableCreatedID(v *int64) *SurveyQuestionCreate {
	if v != nil {
		_c.SetCreatedID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SurveyQuestionCreate) SetStatus(v int64) *SurveyQuestionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableStatus(v *int64) *SurveyQuestionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSurveyID sets the "survey_id" field.
func (_c *SurveyQuestionCreate) SetSurveyID(v int64) *SurveyQuestionCreate {
	_c.mutation.SetSurveyID(v)
	return _c
}

// SetNillableSurveyID sets the "survey_id" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableSurveyID(v *int64) *SurveyQuestionCreate {
	if v != nil {
		_c.SetSurveyID(*v)
	}
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *SurveyQuestionCreate) SetParentID(v int64) *SurveyQuestionCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableParentID(v *int64) *SurveyQuestionCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetSerial sets the "serial" field.
func (_c *SurveyQuestionCreate) SetSerial(v string) *SurveyQuestionCreate {
	_c.mutation.SetSerial(v)
	return _c
}

// SetNillableSerial sets the "serial" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableSerial(v *string) *SurveyQuestionCreate {
	if v != nil {
		_c.SetSerial(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *SurveyQuestionCreate) SetContent(v string) *SurveyQuestionCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableContent(v *string) *SurveyQuestionCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *SurveyQuestionCreate) SetType(v string) *SurveyQuestionCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableType(v *string) *SurveyQuestionCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetOptions sets the "options" field.
func (_c *SurveyQuestionCreate) SetOptions(v []*service.Options) *SurveyQuestionCreate {
	_c.mutation.SetOptions(v)
	return _c
}

// SetShow sets the "show" field.
func (_c *SurveyQuestionCreate) SetShow(v int64) *SurveyQuestionCreate {
	_c.mutation.SetShow(v)
	return _c
}

// SetNillableShow sets the "show" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableShow(v *int64) *SurveyQuestionCreate {
	if v != nil {
		_c.SetShow(*v)
	}
	return _c
}

// SetSort sets the "sort" field.
func (_c *SurveyQuestionCreate) SetSort(v int64) *SurveyQuestionCreate {
	_c.mutation.SetSort(v)
	return _c
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableSort(v *int64) *SurveyQuestionCreate {
	if v != nil {
		_c.SetSort(*v)
	}
	return _c
}

// SetJumpRules sets the "jump_rules" field.
func (_c *SurveyQuestionCreate) SetJumpRules(v []*service.JumpRules) *SurveyQuestionCreate {
	_c.mutation.SetJumpRules(v)
	return _c
}

// SetRequired sets the "required" field.
func (_c *SurveyQuestionCreate) SetRequired(v int64) *SurveyQuestionCreate {
	_c.mutation.SetRequired(v)
	return _c
}

// SetNillableRequired sets the "required" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableRequired(v *int64) *SurveyQuestionCreate {
	if v != nil {
		_c.SetRequired(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *SurveyQuestionCreate) SetRemark(v string) *SurveyQuestionCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableRemark(v *string) *SurveyQuestionCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetLevel sets the "level" field.
func (_c *SurveyQuestionCreate) SetLevel(v int64) *SurveyQuestionCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableLevel(v *int64) *SurveyQuestionCreate {
	if v != nil {
		_c.SetLevel(*v)
	}
	return _c
}

// SetTree sets the "tree" field.
func (_c *SurveyQuestionCreate) SetTree(v string) *SurveyQuestionCreate {
	_c.mutation.SetTree(v)
	return _c
}

// SetNillableTree sets the "tree" field if the given value is not nil.
func (_c *SurveyQuestionCreate) SetNillableTree(v *string) *SurveyQuestionCreate {
	if v != nil {
		_c.SetTree(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SurveyQuestionCreate) SetID(v int64) *SurveyQuestionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSurvey sets the "survey" edge to the Survey entity.
func (_c *SurveyQuestionCreate) SetSurvey(v *Survey) *SurveyQuestionCreate {
	return _c.SetSurveyID(v.ID)
}

// AddAnswerIDs adds the "answers" edge to the SurveyResponseAnswers entity by IDs.
func (_c *SurveyQuestionCreate) AddAnswerIDs(ids ...int64) *SurveyQuestionCreate {
	_c.mutation.AddAnswerIDs(ids...)
	return _c
}

// AddAnswers adds the "answers" edges to the SurveyResponseAnswers entity.
func (_c *SurveyQuestionCreate) AddAnswers(v ...*SurveyResponseAnswers) *SurveyQuestionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAnswerIDs(ids...)
}

// Mutation returns the SurveyQuestionMutation object of the builder.
func (_c *SurveyQuestionCreate) Mutation() *SurveyQuestionMutation {
	return _c.mutation
}

// Save creates the SurveyQuestion in the database.
func (_c *SurveyQuestionCreate) Save(ctx context.Context) (*SurveyQuestion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SurveyQuestionCreate) SaveX(ctx context.Context) *SurveyQuestion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SurveyQuestionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SurveyQuestionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SurveyQuestionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := surveyquestion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := surveyquestion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Delete(); !ok {
		v := surveyquestion.DefaultDelete
		_c.mutation.SetDelete(v)
	}
	if _, ok := _c.mutation.CreatedID(); !ok {
		v := surveyquestion.DefaultCreatedID
		_c.mutation.SetCreatedID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := surveyquestion.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SurveyID(); !ok {
		v := surveyquestion.DefaultSurveyID
		_c.mutation.SetSurveyID(v)
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		v := surveyquestion.DefaultParentID
		_c.mutation.SetParentID(v)
	}
	if _, ok := _c.mutation.Serial(); !ok {
		v := surveyquestion.DefaultSerial
		_c.mutation.SetSerial(v)
	}
	if _, ok := _c.mutation.Content(); !ok {
		v := surveyquestion.DefaultContent
		_c.mutation.SetContent(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := surveyquestion.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Show(); !ok {
		v := surveyquestion.DefaultShow
		_c.mutation.SetShow(v)
	}
	if _, ok := _c.mutation.Sort(); !ok {
		v := surveyquestion.DefaultSort
		_c.mutation.SetSort(v)
	}
	if _, ok := _c.mutation.JumpRules(); !ok {
		v := surveyquestion.DefaultJumpRules
		_c.mutation.SetJumpRules(v)
	}
	if _, ok := _c.mutation.Required(); !ok {
		v := surveyquestion.DefaultRequired
		_c.mutation.SetRequired(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := surveyquestion.DefaultRemark
		_c.mutation.SetRemark(v)
	}
	if _, ok := _c.mutation.Level(); !ok {
		v := surveyquestion.DefaultLevel
		_c.mutation.SetLevel(v)
	}
	if _, ok := _c.mutation.Tree(); !ok {
		v := surveyquestion.DefaultTree
		_c.mutation.SetTree(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SurveyQuestionCreate) check() error {
	return nil
}

func (_c *SurveyQuestionCreate) sqlSave(ctx context.Context) (*SurveyQuestion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SurveyQuestionCreate) createSpec() (*SurveyQuestion, *sqlgraph.CreateSpec) {
	var (
		_node = &SurveyQuestion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(surveyquestion.Table, sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(surveyquestion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(surveyquestion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Delete(); ok {
		_spec.SetField(surveyquestion.FieldDelete, field.TypeInt64, value)
		_node.Delete = value
	}
	if value, ok := _c.mutation.CreatedID(); ok {
		_spec.SetField(surveyquestion.FieldCreatedID, field.TypeInt64, value)
		_node.CreatedID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(surveyquestion.FieldStatus, field.TypeInt64, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(surveyquestion.FieldParentID, field.TypeInt64, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.Serial(); ok {
		_spec.SetField(surveyquestion.FieldSerial, field.TypeString, value)
		_node.Serial = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(surveyquestion.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(surveyquestion.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Options(); ok {
		_spec.SetField(surveyquestion.FieldOptions, field.TypeJSON, value)
		_node.Options = value
	}
	if value, ok := _c.mutation.Show(); ok {
		_spec.SetField(surveyquestion.FieldShow, field.TypeInt64, value)
		_node.Show = value
	}
	if value, ok := _c.mutation.Sort(); ok {
		_spec.SetField(surveyquestion.FieldSort, field.TypeInt64, value)
		_node.Sort = value
	}
	if value, ok := _c.mutation.JumpRules(); ok {
		_spec.SetField(surveyquestion.FieldJumpRules, field.TypeJSON, value)
		_node.JumpRules = value
	}
	if value, ok := _c.mutation.Required(); ok {
		_spec.SetField(surveyquestion.FieldRequired, field.TypeInt64, value)
		_node.Required = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(surveyquestion.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(surveyquestion.FieldLevel, field.TypeInt64, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Tree(); ok {
		_spec.SetField(surveyquestion.FieldTree, field.TypeString, value)
		_node.Tree = value
	}
	if nodes := _c.mutation.SurveyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   surveyquestion.SurveyTable,
			Columns: []string{surveyquestion.SurveyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(survey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SurveyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   surveyquestion.AnswersTable,
			Columns: []string{surveyquestion.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyresponseanswers.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SurveyQuestionCreateBulk is the builder for creating many SurveyQuestion entities in bulk.
type SurveyQuestionCreateBulk struct {
	config
	err      error
	builders []*SurveyQuestionCreate
}

// Save creates the SurveyQuestion entities in the database.
func (_c *SurveyQuestionCreateBulk) Save(ctx context.Context) ([]*SurveyQuestion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SurveyQuestion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SurveyQuestionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SurveyQuestionCreateBulk) SaveX(ctx context.Context) []*SurveyQuestion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SurveyQuestionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SurveyQuestionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
