// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"kcers-survey/biz/dal/db/mysql/ent/predicate"
	"kcers-survey/biz/dal/db/mysql/ent/survey"
	"kcers-survey/biz/dal/db/mysql/ent/surveyquestion"
	"kcers-survey/biz/dal/db/mysql/ent/surveyresponse"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SurveyQuery is the builder for querying Survey entities.
type SurveyQuery struct {
	config
	ctx          *QueryContext
	order        []survey.OrderOption
	inters       []Interceptor
	predicates   []predicate.Survey
	withQuestion *SurveyQuestionQuery
	withResponse *SurveyResponseQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SurveyQuery builder.
func (_q *SurveyQuery) Where(ps ...predicate.Survey) *SurveyQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SurveyQuery) Limit(limit int) *SurveyQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SurveyQuery) Offset(offset int) *SurveyQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SurveyQuery) Unique(unique bool) *SurveyQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SurveyQuery) Order(o ...survey.OrderOption) *SurveyQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryQuestion chains the current query on the "question" edge.
func (_q *SurveyQuery) QueryQuestion() *SurveyQuestionQuery {
	query := (&SurveyQuestionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(survey.Table, survey.FieldID, selector),
			sqlgraph.To(surveyquestion.Table, surveyquestion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, survey.QuestionTable, survey.QuestionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryResponse chains the current query on the "response" edge.
func (_q *SurveyQuery) QueryResponse() *SurveyResponseQuery {
	query := (&SurveyResponseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(survey.Table, survey.FieldID, selector),
			sqlgraph.To(surveyresponse.Table, surveyresponse.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, survey.ResponseTable, survey.ResponseColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Survey entity from the query.
// Returns a *NotFoundError when no Survey was found.
func (_q *SurveyQuery) First(ctx context.Context) (*Survey, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{survey.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SurveyQuery) FirstX(ctx context.Context) *Survey {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Survey ID from the query.
// Returns a *NotFoundError when no Survey ID was found.
func (_q *SurveyQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{survey.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SurveyQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Survey entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Survey entity is found.
// Returns a *NotFoundError when no Survey entities are found.
func (_q *SurveyQuery) Only(ctx context.Context) (*Survey, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{survey.Label}
	default:
		return nil, &NotSingularError{survey.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SurveyQuery) OnlyX(ctx context.Context) *Survey {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Survey ID in the query.
// Returns a *NotSingularError when more than one Survey ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SurveyQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{survey.Label}
	default:
		err = &NotSingularError{survey.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SurveyQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Surveys.
func (_q *SurveyQuery) All(ctx context.Context) ([]*Survey, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Survey, *SurveyQuery]()
	return withInterceptors[[]*Survey](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SurveyQuery) AllX(ctx context.Context) []*Survey {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Survey IDs.
func (_q *SurveyQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(survey.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SurveyQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SurveyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SurveyQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SurveyQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SurveyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SurveyQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SurveyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SurveyQuery) Clone() *SurveyQuery {
	if _q == nil {
		return nil
	}
	return &SurveyQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]survey.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.Survey{}, _q.predicates...),
		withQuestion: _q.withQuestion.Clone(),
		withResponse: _q.withResponse.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithQuestion tells the query-builder to eager-load the nodes that are connected to
// the "question" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SurveyQuery) WithQuestion(opts ...func(*SurveyQuestionQuery)) *SurveyQuery {
	query := (&SurveyQuestionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withQuestion = query
	return _q
}

// WithResponse tells the query-builder to eager-load the nodes that are connected to
// the "response" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SurveyQuery) WithResponse(opts ...func(*SurveyResponseQuery)) *SurveyQuery {
	query := (&SurveyResponseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withResponse = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Survey.Query().
//		GroupBy(survey.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SurveyQuery) GroupBy(field string, fields ...string) *SurveyGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SurveyGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = survey.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Survey.Query().
//		Select(survey.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *SurveyQuery) Select(fields ...string) *SurveySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SurveySelect{SurveyQuery: _q}
	sbuild.label = survey.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SurveySelect configured with the given aggregations.
func (_q *SurveyQuery) Aggregate(fns ...AggregateFunc) *SurveySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SurveyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !survey.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SurveyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Survey, error) {
	var (
		nodes       = []*Survey{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withQuestion != nil,
			_q.withResponse != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Survey).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Survey{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withQuestion; query != nil {
		if err := _q.loadQuestion(ctx, query, nodes,
			func(n *Survey) { n.Edges.Question = []*SurveyQuestion{} },
			func(n *Survey, e *SurveyQuestion) { n.Edges.Question = append(n.Edges.Question, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withResponse; query != nil {
		if err := _q.loadResponse(ctx, query, nodes,
			func(n *Survey) { n.Edges.Response = []*SurveyResponse{} },
			func(n *Survey, e *SurveyResponse) { n.Edges.Response = append(n.Edges.Response, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SurveyQuery) loadQuestion(ctx context.Context, query *SurveyQuestionQuery, nodes []*Survey, init func(*Survey), assign func(*Survey, *SurveyQuestion)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Survey)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(surveyquestion.FieldSurveyID)
	}
	query.Where(predicate.SurveyQuestion(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(survey.QuestionColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SurveyID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "survey_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *SurveyQuery) loadResponse(ctx context.Context, query *SurveyResponseQuery, nodes []*Survey, init func(*Survey), assign func(*Survey, *SurveyResponse)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Survey)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(surveyresponse.FieldSurveyID)
	}
	query.Where(predicate.SurveyResponse(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(survey.ResponseColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SurveyID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "survey_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SurveyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SurveyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(survey.Table, survey.Columns, sqlgraph.NewFieldSpec(survey.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, survey.FieldID)
		for i := range fields {
			if fields[i] != survey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SurveyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(survey.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = survey.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *SurveyQuery) Modify(modifiers ...func(s *sql.Selector)) *SurveySelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// SurveyGroupBy is the group-by builder for Survey entities.
type SurveyGroupBy struct {
	selector
	build *SurveyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SurveyGroupBy) Aggregate(fns ...AggregateFunc) *SurveyGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SurveyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SurveyQuery, *SurveyGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SurveyGroupBy) sqlScan(ctx context.Context, root *SurveyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SurveySelect is the builder for selecting fields of Survey entities.
type SurveySelect struct {
	*SurveyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SurveySelect) Aggregate(fns ...AggregateFunc) *SurveySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SurveySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SurveyQuery, *SurveySelect](ctx, _s.SurveyQuery, _s, _s.inters, v)
}

func (_s *SurveySelect) sqlScan(ctx context.Context, root *SurveyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *SurveySelect) Modify(modifiers ...func(s *sql.Selector)) *SurveySelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
