// Code generated by hertz generator.

package sys

import (
	"context"
	sysService "kcers-survey/biz/infras/service/common"
	"kcers-survey/biz/pkg/errno"
	"kcers-survey/biz/pkg/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	base "kcers-survey/idl_gen/model/base"
	sys "kcers-survey/idl_gen/model/sys"
)

// RoleList .
// @router /service/sys/role/list [POST]
func RoleList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sys.SysListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.NilResponse)

	c.JSON(consts.StatusOK, resp)
}

// Area .
// @router /service/sys/area [GET]
func Area(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sys.SysListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		utils.SendResponse(c, errno.ConvertErr(err), nil, 0, "")
		return
	}
	list, total, err := sysService.NewSys(ctx, c).Area(&req)
	if err != nil {
		utils.SendResponse(c, errno.ConvertErr(err), nil, 0, "")
		return
	}
	utils.SendResponse(c, errno.Success, list, int64(total), "")
	return
}

// City .
// @router /service/sys/city [GET]
func City(ctx context.Context, c *app.RequestContext) {
	var err error
	var req sys.SysListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		utils.SendResponse(c, errno.ConvertErr(err), nil, 0, "")
		return
	}
	list, total, err := sysService.NewSys(ctx, c).City(&req)
	if err != nil {
		utils.SendResponse(c, errno.ConvertErr(err), nil, 0, "")
		return
	}
	utils.SendResponse(c, errno.Success, list, int64(total), "")
	return
}
