// Code generated by ent, DO NOT EDIT.

package surveyquestion

import (
	"kcers-survey/biz/dal/db/mysql/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldUpdatedAt, v))
}

// Delete applies equality check predicate on the "delete" field. It's identical to DeleteEQ.
func Delete(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldDelete, v))
}

// CreatedID applies equality check predicate on the "created_id" field. It's identical to CreatedIDEQ.
func CreatedID(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldCreatedID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldStatus, v))
}

// SurveyID applies equality check predicate on the "survey_id" field. It's identical to SurveyIDEQ.
func SurveyID(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldSurveyID, v))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldParentID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldContent, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldType, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldSort, v))
}

// Required applies equality check predicate on the "required" field. It's identical to RequiredEQ.
func Required(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldRequired, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldUpdatedAt))
}

// DeleteEQ applies the EQ predicate on the "delete" field.
func DeleteEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldDelete, v))
}

// DeleteNEQ applies the NEQ predicate on the "delete" field.
func DeleteNEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldDelete, v))
}

// DeleteIn applies the In predicate on the "delete" field.
func DeleteIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldDelete, vs...))
}

// DeleteNotIn applies the NotIn predicate on the "delete" field.
func DeleteNotIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldDelete, vs...))
}

// DeleteGT applies the GT predicate on the "delete" field.
func DeleteGT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGT(FieldDelete, v))
}

// DeleteGTE applies the GTE predicate on the "delete" field.
func DeleteGTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGTE(FieldDelete, v))
}

// DeleteLT applies the LT predicate on the "delete" field.
func DeleteLT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLT(FieldDelete, v))
}

// DeleteLTE applies the LTE predicate on the "delete" field.
func DeleteLTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLTE(FieldDelete, v))
}

// DeleteIsNil applies the IsNil predicate on the "delete" field.
func DeleteIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldDelete))
}

// DeleteNotNil applies the NotNil predicate on the "delete" field.
func DeleteNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldDelete))
}

// CreatedIDEQ applies the EQ predicate on the "created_id" field.
func CreatedIDEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldCreatedID, v))
}

// CreatedIDNEQ applies the NEQ predicate on the "created_id" field.
func CreatedIDNEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldCreatedID, v))
}

// CreatedIDIn applies the In predicate on the "created_id" field.
func CreatedIDIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldCreatedID, vs...))
}

// CreatedIDNotIn applies the NotIn predicate on the "created_id" field.
func CreatedIDNotIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldCreatedID, vs...))
}

// CreatedIDGT applies the GT predicate on the "created_id" field.
func CreatedIDGT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGT(FieldCreatedID, v))
}

// CreatedIDGTE applies the GTE predicate on the "created_id" field.
func CreatedIDGTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGTE(FieldCreatedID, v))
}

// CreatedIDLT applies the LT predicate on the "created_id" field.
func CreatedIDLT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLT(FieldCreatedID, v))
}

// CreatedIDLTE applies the LTE predicate on the "created_id" field.
func CreatedIDLTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLTE(FieldCreatedID, v))
}

// CreatedIDIsNil applies the IsNil predicate on the "created_id" field.
func CreatedIDIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldCreatedID))
}

// CreatedIDNotNil applies the NotNil predicate on the "created_id" field.
func CreatedIDNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldCreatedID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLTE(FieldStatus, v))
}

// StatusIsNil applies the IsNil predicate on the "status" field.
func StatusIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldStatus))
}

// StatusNotNil applies the NotNil predicate on the "status" field.
func StatusNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldStatus))
}

// SurveyIDEQ applies the EQ predicate on the "survey_id" field.
func SurveyIDEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldSurveyID, v))
}

// SurveyIDNEQ applies the NEQ predicate on the "survey_id" field.
func SurveyIDNEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldSurveyID, v))
}

// SurveyIDIn applies the In predicate on the "survey_id" field.
func SurveyIDIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldSurveyID, vs...))
}

// SurveyIDNotIn applies the NotIn predicate on the "survey_id" field.
func SurveyIDNotIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldSurveyID, vs...))
}

// SurveyIDIsNil applies the IsNil predicate on the "survey_id" field.
func SurveyIDIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldSurveyID))
}

// SurveyIDNotNil applies the NotNil predicate on the "survey_id" field.
func SurveyIDNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldSurveyID))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLTE(FieldParentID, v))
}

// ParentIDIsNil applies the IsNil predicate on the "parent_id" field.
func ParentIDIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldParentID))
}

// ParentIDNotNil applies the NotNil predicate on the "parent_id" field.
func ParentIDNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldParentID))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldContainsFold(FieldContent, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldHasSuffix(FieldType, v))
}

// TypeIsNil applies the IsNil predicate on the "type" field.
func TypeIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldType))
}

// TypeNotNil applies the NotNil predicate on the "type" field.
func TypeNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldType))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldContainsFold(FieldType, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLTE(FieldSort, v))
}

// SortIsNil applies the IsNil predicate on the "sort" field.
func SortIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldSort))
}

// SortNotNil applies the NotNil predicate on the "sort" field.
func SortNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldSort))
}

// RequiredEQ applies the EQ predicate on the "required" field.
func RequiredEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldEQ(FieldRequired, v))
}

// RequiredNEQ applies the NEQ predicate on the "required" field.
func RequiredNEQ(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNEQ(FieldRequired, v))
}

// RequiredIn applies the In predicate on the "required" field.
func RequiredIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIn(FieldRequired, vs...))
}

// RequiredNotIn applies the NotIn predicate on the "required" field.
func RequiredNotIn(vs ...int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotIn(FieldRequired, vs...))
}

// RequiredGT applies the GT predicate on the "required" field.
func RequiredGT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGT(FieldRequired, v))
}

// RequiredGTE applies the GTE predicate on the "required" field.
func RequiredGTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldGTE(FieldRequired, v))
}

// RequiredLT applies the LT predicate on the "required" field.
func RequiredLT(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLT(FieldRequired, v))
}

// RequiredLTE applies the LTE predicate on the "required" field.
func RequiredLTE(v int64) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldLTE(FieldRequired, v))
}

// RequiredIsNil applies the IsNil predicate on the "required" field.
func RequiredIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldRequired))
}

// RequiredNotNil applies the NotNil predicate on the "required" field.
func RequiredNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldRequired))
}

// OptionsIsNil applies the IsNil predicate on the "options" field.
func OptionsIsNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldIsNull(FieldOptions))
}

// OptionsNotNil applies the NotNil predicate on the "options" field.
func OptionsNotNil() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.FieldNotNull(FieldOptions))
}

// HasSurvey applies the HasEdge predicate on the "survey" edge.
func HasSurvey() predicate.SurveyQuestion {
	return predicate.SurveyQuestion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SurveyTable, SurveyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSurveyWith applies the HasEdge predicate on the "survey" edge with a given conditions (other predicates).
func HasSurveyWith(preds ...predicate.Survey) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(func(s *sql.Selector) {
		step := newSurveyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SurveyQuestion) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SurveyQuestion) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SurveyQuestion) predicate.SurveyQuestion {
	return predicate.SurveyQuestion(sql.NotPredicates(p))
}
