// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	pub "kcers-survey/biz/router/pub"
	service "kcers-survey/biz/router/service"
	user "kcers-survey/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	pub.Register(r)

	user.Register(r)

	service.Register(r)
}
