services:
  nginx:
    image: nginx:alpine  # 关键！用alpine版，镜像仅20MB，比标准版省300MB内存
    network_mode: host   # 使用宿主机网络
    restart: always
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro          # 主配置
      - ./data/nginx/conf.d:/etc/nginx/conf.d:ro                  # ★ vhost目录挂载
      - ./data/nginx/ssl:/etc/nginx/ssl:ro                        # 证书目录
      - ./data/nginx/logs:/var/log/nginx                          # 日志目录
      - /home/www:/home/www
      - ./data/fastdfs_data/files:/home/files
      - /home/wwwlogs:/home/wwwlogs

    extra_hosts:
      - "host.docker.internal:host-gateway"  # 如需访问宿主机服务

  fastdfs:
    image: sjqzhang/go-fastdfs
    environment:
      - GO_FASTDFS_DIR=/data
    volumes:
      - ./data/fastdfs_data:/data
    ports:
      - "9109:8080"

  RabbitMQ:
    image: rapidfort/rabbitmq-official:4.1.8-management-alpine
    container_name: mq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: kcersing
      RABBITMQ_DEFAULT_PASS: kcer-913639
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "+MMscs 512"
      TZ: Asia/Shanghai
      LANG: zh_CN.UTF-8
