// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kcers-survey/biz/dal/db/mysql/ent/menu"
	"kcers-survey/biz/dal/db/mysql/ent/menuparam"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MenuParamCreate is the builder for creating a MenuParam entity.
type MenuParamCreate struct {
	config
	mutation *MenuParamMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *MenuParamCreate) SetCreatedAt(v time.Time) *MenuParamCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MenuParamCreate) SetNillableCreatedAt(v *time.Time) *MenuParamCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MenuParamCreate) SetUpdatedAt(v time.Time) *MenuParamCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MenuParamCreate) SetNillableUpdatedAt(v *time.Time) *MenuParamCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDelete sets the "delete" field.
func (_c *MenuParamCreate) SetDelete(v int64) *MenuParamCreate {
	_c.mutation.SetDelete(v)
	return _c
}

// SetNillableDelete sets the "delete" field if the given value is not nil.
func (_c *MenuParamCreate) SetNillableDelete(v *int64) *MenuParamCreate {
	if v != nil {
		_c.SetDelete(*v)
	}
	return _c
}

// SetCreatedID sets the "created_id" field.
func (_c *MenuParamCreate) SetCreatedID(v int64) *MenuParamCreate {
	_c.mutation.SetCreatedID(v)
	return _c
}

// SetNillableCreatedID sets the "created_id" field if the given value is not nil.
func (_c *MenuParamCreate) SetNillableCreatedID(v *int64) *MenuParamCreate {
	if v != nil {
		_c.SetCreatedID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *MenuParamCreate) SetType(v string) *MenuParamCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *MenuParamCreate) SetKey(v string) *MenuParamCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *MenuParamCreate) SetValue(v string) *MenuParamCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MenuParamCreate) SetID(v int64) *MenuParamCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetMenusID sets the "menus" edge to the Menu entity by ID.
func (_c *MenuParamCreate) SetMenusID(id int64) *MenuParamCreate {
	_c.mutation.SetMenusID(id)
	return _c
}

// SetNillableMenusID sets the "menus" edge to the Menu entity by ID if the given value is not nil.
func (_c *MenuParamCreate) SetNillableMenusID(id *int64) *MenuParamCreate {
	if id != nil {
		_c = _c.SetMenusID(*id)
	}
	return _c
}

// SetMenus sets the "menus" edge to the Menu entity.
func (_c *MenuParamCreate) SetMenus(v *Menu) *MenuParamCreate {
	return _c.SetMenusID(v.ID)
}

// Mutation returns the MenuParamMutation object of the builder.
func (_c *MenuParamCreate) Mutation() *MenuParamMutation {
	return _c.mutation
}

// Save creates the MenuParam in the database.
func (_c *MenuParamCreate) Save(ctx context.Context) (*MenuParam, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MenuParamCreate) SaveX(ctx context.Context) *MenuParam {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MenuParamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MenuParamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MenuParamCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := menuparam.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := menuparam.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Delete(); !ok {
		v := menuparam.DefaultDelete
		_c.mutation.SetDelete(v)
	}
	if _, ok := _c.mutation.CreatedID(); !ok {
		v := menuparam.DefaultCreatedID
		_c.mutation.SetCreatedID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MenuParamCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "MenuParam.type"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "MenuParam.key"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "MenuParam.value"`)}
	}
	return nil
}

func (_c *MenuParamCreate) sqlSave(ctx context.Context) (*MenuParam, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MenuParamCreate) createSpec() (*MenuParam, *sqlgraph.CreateSpec) {
	var (
		_node = &MenuParam{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(menuparam.Table, sqlgraph.NewFieldSpec(menuparam.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(menuparam.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(menuparam.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Delete(); ok {
		_spec.SetField(menuparam.FieldDelete, field.TypeInt64, value)
		_node.Delete = value
	}
	if value, ok := _c.mutation.CreatedID(); ok {
		_spec.SetField(menuparam.FieldCreatedID, field.TypeInt64, value)
		_node.CreatedID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(menuparam.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(menuparam.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(menuparam.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if nodes := _c.mutation.MenusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   menuparam.MenusTable,
			Columns: []string{menuparam.MenusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(menu.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.menu_params = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MenuParamCreateBulk is the builder for creating many MenuParam entities in bulk.
type MenuParamCreateBulk struct {
	config
	err      error
	builders []*MenuParamCreate
}

// Save creates the MenuParam entities in the database.
func (_c *MenuParamCreateBulk) Save(ctx context.Context) ([]*MenuParam, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MenuParam, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MenuParamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MenuParamCreateBulk) SaveX(ctx context.Context) []*MenuParam {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MenuParamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MenuParamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
