// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"kcers-survey/biz/dal/db/mysql/ent/predicate"
	"kcers-survey/biz/dal/db/mysql/ent/surveyresponseanswers"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SurveyResponseAnswersDelete is the builder for deleting a SurveyResponseAnswers entity.
type SurveyResponseAnswersDelete struct {
	config
	hooks    []Hook
	mutation *SurveyResponseAnswersMutation
}

// Where appends a list predicates to the SurveyResponseAnswersDelete builder.
func (_d *SurveyResponseAnswersDelete) Where(ps ...predicate.SurveyResponseAnswers) *SurveyResponseAnswersDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SurveyResponseAnswersDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SurveyResponseAnswersDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SurveyResponseAnswersDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(surveyresponseanswers.Table, sqlgraph.NewFieldSpec(surveyresponseanswers.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SurveyResponseAnswersDeleteOne is the builder for deleting a single SurveyResponseAnswers entity.
type SurveyResponseAnswersDeleteOne struct {
	_d *SurveyResponseAnswersDelete
}

// Where appends a list predicates to the SurveyResponseAnswersDelete builder.
func (_d *SurveyResponseAnswersDeleteOne) Where(ps ...predicate.SurveyResponseAnswers) *SurveyResponseAnswersDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SurveyResponseAnswersDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{surveyresponseanswers.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SurveyResponseAnswersDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
