// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"kcers-survey/biz/dal/db/mysql/ent/predicate"
	"kcers-survey/biz/dal/db/mysql/ent/survey"
	"kcers-survey/biz/dal/db/mysql/ent/surveyquestion"
	"kcers-survey/biz/dal/db/mysql/ent/surveyresponse"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SurveyUpdate is the builder for updating Survey entities.
type SurveyUpdate struct {
	config
	hooks     []Hook
	mutation  *SurveyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SurveyUpdate builder.
func (_u *SurveyUpdate) Where(ps ...predicate.Survey) *SurveyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SurveyUpdate) SetUpdatedAt(v time.Time) *SurveyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SurveyUpdate) ClearUpdatedAt() *SurveyUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDelete sets the "delete" field.
func (_u *SurveyUpdate) SetDelete(v int64) *SurveyUpdate {
	_u.mutation.ResetDelete()
	_u.mutation.SetDelete(v)
	return _u
}

// SetNillableDelete sets the "delete" field if the given value is not nil.
func (_u *SurveyUpdate) SetNillableDelete(v *int64) *SurveyUpdate {
	if v != nil {
		_u.SetDelete(*v)
	}
	return _u
}

// AddDelete adds value to the "delete" field.
func (_u *SurveyUpdate) AddDelete(v int64) *SurveyUpdate {
	_u.mutation.AddDelete(v)
	return _u
}

// ClearDelete clears the value of the "delete" field.
func (_u *SurveyUpdate) ClearDelete() *SurveyUpdate {
	_u.mutation.ClearDelete()
	return _u
}

// SetCreatedID sets the "created_id" field.
func (_u *SurveyUpdate) SetCreatedID(v int64) *SurveyUpdate {
	_u.mutation.ResetCreatedID()
	_u.mutation.SetCreatedID(v)
	return _u
}

// SetNillableCreatedID sets the "created_id" field if the given value is not nil.
func (_u *SurveyUpdate) SetNillableCreatedID(v *int64) *SurveyUpdate {
	if v != nil {
		_u.SetCreatedID(*v)
	}
	return _u
}

// AddCreatedID adds value to the "created_id" field.
func (_u *SurveyUpdate) AddCreatedID(v int64) *SurveyUpdate {
	_u.mutation.AddCreatedID(v)
	return _u
}

// ClearCreatedID clears the value of the "created_id" field.
func (_u *SurveyUpdate) ClearCreatedID() *SurveyUpdate {
	_u.mutation.ClearCreatedID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SurveyUpdate) SetStatus(v int64) *SurveyUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SurveyUpdate) SetNillableStatus(v *int64) *SurveyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *SurveyUpdate) AddStatus(v int64) *SurveyUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *SurveyUpdate) ClearStatus() *SurveyUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetTitle sets the "title" field.
func (_u *SurveyUpdate) SetTitle(v string) *SurveyUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SurveyUpdate) SetNillableTitle(v *string) *SurveyUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *SurveyUpdate) ClearTitle() *SurveyUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetPic sets the "pic" field.
func (_u *SurveyUpdate) SetPic(v string) *SurveyUpdate {
	_u.mutation.SetPic(v)
	return _u
}

// SetNillablePic sets the "pic" field if the given value is not nil.
func (_u *SurveyUpdate) SetNillablePic(v *string) *SurveyUpdate {
	if v != nil {
		_u.SetPic(*v)
	}
	return _u
}

// ClearPic clears the value of the "pic" field.
func (_u *SurveyUpdate) ClearPic() *SurveyUpdate {
	_u.mutation.ClearPic()
	return _u
}

// SetDesc sets the "desc" field.
func (_u *SurveyUpdate) SetDesc(v string) *SurveyUpdate {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *SurveyUpdate) SetNillableDesc(v *string) *SurveyUpdate {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// ClearDesc clears the value of the "desc" field.
func (_u *SurveyUpdate) ClearDesc() *SurveyUpdate {
	_u.mutation.ClearDesc()
	return _u
}

// SetStartAt sets the "start_at" field.
func (_u *SurveyUpdate) SetStartAt(v time.Time) *SurveyUpdate {
	_u.mutation.SetStartAt(v)
	return _u
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_u *SurveyUpdate) SetNillableStartAt(v *time.Time) *SurveyUpdate {
	if v != nil {
		_u.SetStartAt(*v)
	}
	return _u
}

// ClearStartAt clears the value of the "start_at" field.
func (_u *SurveyUpdate) ClearStartAt() *SurveyUpdate {
	_u.mutation.ClearStartAt()
	return _u
}

// SetEndAt sets the "end_at" field.
func (_u *SurveyUpdate) SetEndAt(v time.Time) *SurveyUpdate {
	_u.mutation.SetEndAt(v)
	return _u
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_u *SurveyUpdate) SetNillableEndAt(v *time.Time) *SurveyUpdate {
	if v != nil {
		_u.SetEndAt(*v)
	}
	return _u
}

// ClearEndAt clears the value of the "end_at" field.
func (_u *SurveyUpdate) ClearEndAt() *SurveyUpdate {
	_u.mutation.ClearEndAt()
	return _u
}

// AddQuestionIDs adds the "question" edge to the SurveyQuestion entity by IDs.
func (_u *SurveyUpdate) AddQuestionIDs(ids ...int64) *SurveyUpdate {
	_u.mutation.AddQuestionIDs(ids...)
	return _u
}

// AddQuestion adds the "question" edges to the SurveyQuestion entity.
func (_u *SurveyUpdate) AddQuestion(v ...*SurveyQuestion) *SurveyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuestionIDs(ids...)
}

// AddResponseIDs adds the "response" edge to the SurveyResponse entity by IDs.
func (_u *SurveyUpdate) AddResponseIDs(ids ...int64) *SurveyUpdate {
	_u.mutation.AddResponseIDs(ids...)
	return _u
}

// AddResponse adds the "response" edges to the SurveyResponse entity.
func (_u *SurveyUpdate) AddResponse(v ...*SurveyResponse) *SurveyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseIDs(ids...)
}

// Mutation returns the SurveyMutation object of the builder.
func (_u *SurveyUpdate) Mutation() *SurveyMutation {
	return _u.mutation
}

// ClearQuestion clears all "question" edges to the SurveyQuestion entity.
func (_u *SurveyUpdate) ClearQuestion() *SurveyUpdate {
	_u.mutation.ClearQuestion()
	return _u
}

// RemoveQuestionIDs removes the "question" edge to SurveyQuestion entities by IDs.
func (_u *SurveyUpdate) RemoveQuestionIDs(ids ...int64) *SurveyUpdate {
	_u.mutation.RemoveQuestionIDs(ids...)
	return _u
}

// RemoveQuestion removes "question" edges to SurveyQuestion entities.
func (_u *SurveyUpdate) RemoveQuestion(v ...*SurveyQuestion) *SurveyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuestionIDs(ids...)
}

// ClearResponse clears all "response" edges to the SurveyResponse entity.
func (_u *SurveyUpdate) ClearResponse() *SurveyUpdate {
	_u.mutation.ClearResponse()
	return _u
}

// RemoveResponseIDs removes the "response" edge to SurveyResponse entities by IDs.
func (_u *SurveyUpdate) RemoveResponseIDs(ids ...int64) *SurveyUpdate {
	_u.mutation.RemoveResponseIDs(ids...)
	return _u
}

// RemoveResponse removes "response" edges to SurveyResponse entities.
func (_u *SurveyUpdate) RemoveResponse(v ...*SurveyResponse) *SurveyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SurveyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SurveyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SurveyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SurveyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SurveyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := survey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SurveyUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SurveyUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SurveyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(survey.Table, survey.Columns, sqlgraph.NewFieldSpec(survey.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(survey.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(survey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(survey.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Delete(); ok {
		_spec.SetField(survey.FieldDelete, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDelete(); ok {
		_spec.AddField(survey.FieldDelete, field.TypeInt64, value)
	}
	if _u.mutation.DeleteCleared() {
		_spec.ClearField(survey.FieldDelete, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedID(); ok {
		_spec.SetField(survey.FieldCreatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedID(); ok {
		_spec.AddField(survey.FieldCreatedID, field.TypeInt64, value)
	}
	if _u.mutation.CreatedIDCleared() {
		_spec.ClearField(survey.FieldCreatedID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(survey.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(survey.FieldStatus, field.TypeInt64, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(survey.FieldStatus, field.TypeInt64)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(survey.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(survey.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Pic(); ok {
		_spec.SetField(survey.FieldPic, field.TypeString, value)
	}
	if _u.mutation.PicCleared() {
		_spec.ClearField(survey.FieldPic, field.TypeString)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(survey.FieldDesc, field.TypeString, value)
	}
	if _u.mutation.DescCleared() {
		_spec.ClearField(survey.FieldDesc, field.TypeString)
	}
	if value, ok := _u.mutation.StartAt(); ok {
		_spec.SetField(survey.FieldStartAt, field.TypeTime, value)
	}
	if _u.mutation.StartAtCleared() {
		_spec.ClearField(survey.FieldStartAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndAt(); ok {
		_spec.SetField(survey.FieldEndAt, field.TypeTime, value)
	}
	if _u.mutation.EndAtCleared() {
		_spec.ClearField(survey.FieldEndAt, field.TypeTime)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.QuestionTable,
			Columns: []string{survey.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuestionIDs(); len(nodes) > 0 && !_u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.QuestionTable,
			Columns: []string{survey.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.QuestionTable,
			Columns: []string{survey.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.ResponseTable,
			Columns: []string{survey.ResponseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyresponse.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponseIDs(); len(nodes) > 0 && !_u.mutation.ResponseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.ResponseTable,
			Columns: []string{survey.ResponseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyresponse.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.ResponseTable,
			Columns: []string{survey.ResponseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyresponse.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{survey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SurveyUpdateOne is the builder for updating a single Survey entity.
type SurveyUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SurveyMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SurveyUpdateOne) SetUpdatedAt(v time.Time) *SurveyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *SurveyUpdateOne) ClearUpdatedAt() *SurveyUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDelete sets the "delete" field.
func (_u *SurveyUpdateOne) SetDelete(v int64) *SurveyUpdateOne {
	_u.mutation.ResetDelete()
	_u.mutation.SetDelete(v)
	return _u
}

// SetNillableDelete sets the "delete" field if the given value is not nil.
func (_u *SurveyUpdateOne) SetNillableDelete(v *int64) *SurveyUpdateOne {
	if v != nil {
		_u.SetDelete(*v)
	}
	return _u
}

// AddDelete adds value to the "delete" field.
func (_u *SurveyUpdateOne) AddDelete(v int64) *SurveyUpdateOne {
	_u.mutation.AddDelete(v)
	return _u
}

// ClearDelete clears the value of the "delete" field.
func (_u *SurveyUpdateOne) ClearDelete() *SurveyUpdateOne {
	_u.mutation.ClearDelete()
	return _u
}

// SetCreatedID sets the "created_id" field.
func (_u *SurveyUpdateOne) SetCreatedID(v int64) *SurveyUpdateOne {
	_u.mutation.ResetCreatedID()
	_u.mutation.SetCreatedID(v)
	return _u
}

// SetNillableCreatedID sets the "created_id" field if the given value is not nil.
func (_u *SurveyUpdateOne) SetNillableCreatedID(v *int64) *SurveyUpdateOne {
	if v != nil {
		_u.SetCreatedID(*v)
	}
	return _u
}

// AddCreatedID adds value to the "created_id" field.
func (_u *SurveyUpdateOne) AddCreatedID(v int64) *SurveyUpdateOne {
	_u.mutation.AddCreatedID(v)
	return _u
}

// ClearCreatedID clears the value of the "created_id" field.
func (_u *SurveyUpdateOne) ClearCreatedID() *SurveyUpdateOne {
	_u.mutation.ClearCreatedID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SurveyUpdateOne) SetStatus(v int64) *SurveyUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SurveyUpdateOne) SetNillableStatus(v *int64) *SurveyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *SurveyUpdateOne) AddStatus(v int64) *SurveyUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *SurveyUpdateOne) ClearStatus() *SurveyUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetTitle sets the "title" field.
func (_u *SurveyUpdateOne) SetTitle(v string) *SurveyUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SurveyUpdateOne) SetNillableTitle(v *string) *SurveyUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *SurveyUpdateOne) ClearTitle() *SurveyUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetPic sets the "pic" field.
func (_u *SurveyUpdateOne) SetPic(v string) *SurveyUpdateOne {
	_u.mutation.SetPic(v)
	return _u
}

// SetNillablePic sets the "pic" field if the given value is not nil.
func (_u *SurveyUpdateOne) SetNillablePic(v *string) *SurveyUpdateOne {
	if v != nil {
		_u.SetPic(*v)
	}
	return _u
}

// ClearPic clears the value of the "pic" field.
func (_u *SurveyUpdateOne) ClearPic() *SurveyUpdateOne {
	_u.mutation.ClearPic()
	return _u
}

// SetDesc sets the "desc" field.
func (_u *SurveyUpdateOne) SetDesc(v string) *SurveyUpdateOne {
	_u.mutation.SetDesc(v)
	return _u
}

// SetNillableDesc sets the "desc" field if the given value is not nil.
func (_u *SurveyUpdateOne) SetNillableDesc(v *string) *SurveyUpdateOne {
	if v != nil {
		_u.SetDesc(*v)
	}
	return _u
}

// ClearDesc clears the value of the "desc" field.
func (_u *SurveyUpdateOne) ClearDesc() *SurveyUpdateOne {
	_u.mutation.ClearDesc()
	return _u
}

// SetStartAt sets the "start_at" field.
func (_u *SurveyUpdateOne) SetStartAt(v time.Time) *SurveyUpdateOne {
	_u.mutation.SetStartAt(v)
	return _u
}

// SetNillableStartAt sets the "start_at" field if the given value is not nil.
func (_u *SurveyUpdateOne) SetNillableStartAt(v *time.Time) *SurveyUpdateOne {
	if v != nil {
		_u.SetStartAt(*v)
	}
	return _u
}

// ClearStartAt clears the value of the "start_at" field.
func (_u *SurveyUpdateOne) ClearStartAt() *SurveyUpdateOne {
	_u.mutation.ClearStartAt()
	return _u
}

// SetEndAt sets the "end_at" field.
func (_u *SurveyUpdateOne) SetEndAt(v time.Time) *SurveyUpdateOne {
	_u.mutation.SetEndAt(v)
	return _u
}

// SetNillableEndAt sets the "end_at" field if the given value is not nil.
func (_u *SurveyUpdateOne) SetNillableEndAt(v *time.Time) *SurveyUpdateOne {
	if v != nil {
		_u.SetEndAt(*v)
	}
	return _u
}

// ClearEndAt clears the value of the "end_at" field.
func (_u *SurveyUpdateOne) ClearEndAt() *SurveyUpdateOne {
	_u.mutation.ClearEndAt()
	return _u
}

// AddQuestionIDs adds the "question" edge to the SurveyQuestion entity by IDs.
func (_u *SurveyUpdateOne) AddQuestionIDs(ids ...int64) *SurveyUpdateOne {
	_u.mutation.AddQuestionIDs(ids...)
	return _u
}

// AddQuestion adds the "question" edges to the SurveyQuestion entity.
func (_u *SurveyUpdateOne) AddQuestion(v ...*SurveyQuestion) *SurveyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuestionIDs(ids...)
}

// AddResponseIDs adds the "response" edge to the SurveyResponse entity by IDs.
func (_u *SurveyUpdateOne) AddResponseIDs(ids ...int64) *SurveyUpdateOne {
	_u.mutation.AddResponseIDs(ids...)
	return _u
}

// AddResponse adds the "response" edges to the SurveyResponse entity.
func (_u *SurveyUpdateOne) AddResponse(v ...*SurveyResponse) *SurveyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponseIDs(ids...)
}

// Mutation returns the SurveyMutation object of the builder.
func (_u *SurveyUpdateOne) Mutation() *SurveyMutation {
	return _u.mutation
}

// ClearQuestion clears all "question" edges to the SurveyQuestion entity.
func (_u *SurveyUpdateOne) ClearQuestion() *SurveyUpdateOne {
	_u.mutation.ClearQuestion()
	return _u
}

// RemoveQuestionIDs removes the "question" edge to SurveyQuestion entities by IDs.
func (_u *SurveyUpdateOne) RemoveQuestionIDs(ids ...int64) *SurveyUpdateOne {
	_u.mutation.RemoveQuestionIDs(ids...)
	return _u
}

// RemoveQuestion removes "question" edges to SurveyQuestion entities.
func (_u *SurveyUpdateOne) RemoveQuestion(v ...*SurveyQuestion) *SurveyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuestionIDs(ids...)
}

// ClearResponse clears all "response" edges to the SurveyResponse entity.
func (_u *SurveyUpdateOne) ClearResponse() *SurveyUpdateOne {
	_u.mutation.ClearResponse()
	return _u
}

// RemoveResponseIDs removes the "response" edge to SurveyResponse entities by IDs.
func (_u *SurveyUpdateOne) RemoveResponseIDs(ids ...int64) *SurveyUpdateOne {
	_u.mutation.RemoveResponseIDs(ids...)
	return _u
}

// RemoveResponse removes "response" edges to SurveyResponse entities.
func (_u *SurveyUpdateOne) RemoveResponse(v ...*SurveyResponse) *SurveyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponseIDs(ids...)
}

// Where appends a list predicates to the SurveyUpdate builder.
func (_u *SurveyUpdateOne) Where(ps ...predicate.Survey) *SurveyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SurveyUpdateOne) Select(field string, fields ...string) *SurveyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Survey entity.
func (_u *SurveyUpdateOne) Save(ctx context.Context) (*Survey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SurveyUpdateOne) SaveX(ctx context.Context) *Survey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SurveyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SurveyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SurveyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := survey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SurveyUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SurveyUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SurveyUpdateOne) sqlSave(ctx context.Context) (_node *Survey, err error) {
	_spec := sqlgraph.NewUpdateSpec(survey.Table, survey.Columns, sqlgraph.NewFieldSpec(survey.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Survey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, survey.FieldID)
		for _, f := range fields {
			if !survey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != survey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(survey.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(survey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(survey.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Delete(); ok {
		_spec.SetField(survey.FieldDelete, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDelete(); ok {
		_spec.AddField(survey.FieldDelete, field.TypeInt64, value)
	}
	if _u.mutation.DeleteCleared() {
		_spec.ClearField(survey.FieldDelete, field.TypeInt64)
	}
	if value, ok := _u.mutation.CreatedID(); ok {
		_spec.SetField(survey.FieldCreatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedID(); ok {
		_spec.AddField(survey.FieldCreatedID, field.TypeInt64, value)
	}
	if _u.mutation.CreatedIDCleared() {
		_spec.ClearField(survey.FieldCreatedID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(survey.FieldStatus, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(survey.FieldStatus, field.TypeInt64, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(survey.FieldStatus, field.TypeInt64)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(survey.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(survey.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Pic(); ok {
		_spec.SetField(survey.FieldPic, field.TypeString, value)
	}
	if _u.mutation.PicCleared() {
		_spec.ClearField(survey.FieldPic, field.TypeString)
	}
	if value, ok := _u.mutation.Desc(); ok {
		_spec.SetField(survey.FieldDesc, field.TypeString, value)
	}
	if _u.mutation.DescCleared() {
		_spec.ClearField(survey.FieldDesc, field.TypeString)
	}
	if value, ok := _u.mutation.StartAt(); ok {
		_spec.SetField(survey.FieldStartAt, field.TypeTime, value)
	}
	if _u.mutation.StartAtCleared() {
		_spec.ClearField(survey.FieldStartAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EndAt(); ok {
		_spec.SetField(survey.FieldEndAt, field.TypeTime, value)
	}
	if _u.mutation.EndAtCleared() {
		_spec.ClearField(survey.FieldEndAt, field.TypeTime)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.QuestionTable,
			Columns: []string{survey.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuestionIDs(); len(nodes) > 0 && !_u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.QuestionTable,
			Columns: []string{survey.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.QuestionTable,
			Columns: []string{survey.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyquestion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.ResponseTable,
			Columns: []string{survey.ResponseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyresponse.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponseIDs(); len(nodes) > 0 && !_u.mutation.ResponseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.ResponseTable,
			Columns: []string{survey.ResponseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyresponse.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   survey.ResponseTable,
			Columns: []string{survey.ResponseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(surveyresponse.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Survey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{survey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
